const rawGroups = [
  {
    id: 'operations',
    label: '操作词',
    tone: '#1f8a5b',
    words: `come, get, give, go, keep, let, make, put, seem, take,
be, do, have, say, see, send, may, will,
about, across, after, against, among, at, before, between, by,
down, from, in, off, on, over, through, to, under, up, with,
as, for, of, till, than,
a, the, all, any, every, little, much, no, other, some, such, that, this,
I, he, you, who,
and, because, but, or, if, though, while, how, when, where, why,
again, ever, far, forward, here, near, now, out, still, then,
there, together, well,
almost, enough, even, not, only, quite, so, very,
tomorrow, yesterday,
north, south, east, west, please, yes`,
  },
  {
    id: 'things',
    label: '一般事物',
    tone: '#2e6f9f',
    words: `account, act, addition, adjustment, advertisement, agreement, air,
amount, amusement, animal, answer, apparatus, approval, argument, art,
attack, attempt, attention, attraction, authority,
back, balance, base, behavior, belief, birth, bit, bite, blood, blow,
body, brass, bread, breath, brother, building, burn, burst, business,
butter,
canvas, care, cause, chalk, chance, change, cloth, coal, color, comfort,
committee, company, comparison, competition, condition, connection,
control, cook, copper, copy, cork, cotton, cough, country, cover,
crack, credit, crime, crush, cry, current, curve,
damage, danger, daughter, day, death, debt, decision, degree, design,
desire, destruction, detail, development, digestion, direction,
discovery, discussion, disease, disgust, distance,
distribution, division, doubt, drink, driving, dust,
earth, edge, education, effect, end, error, event, example, exchange,
existence, expansion, experience, expert,
fact, fall, family, father, fear, feeling, fiction, field, fight, fire,
flame, flight, flower, fold, food, force, form, friend, front, fruit,
glass, gold, government, grain, grass, grip, group, growth, guide,
harbor, harmony, hate, hearing, heat, help, history, hole, hope, hour, humor,
ice, idea, impulse, increase, industry, ink, insect, instrument,
insurance, interest, invention, iron,
jelly, join, journey, judge, jump,
kick, kiss, knowledge,
land, language, laugh, law, lead, learning, leather, letter, level,
lift, light, limit, linen, liquid, list, look, loss, love,
machine, man, manager, mark, market, mass, meal, measure, meat, meeting,
memory, metal, middle, milk, mind, mine, minute, mist, money, month,
morning, mother, motion, mountain, move, music,
name, nation, need, news, night, noise, note, number,
observation, offer, oil, operation, opinion, order, organization,
ornament, owner,
page, pain, paint, paper, part, paste, payment, peace, person, place,
plant, play, pleasure, point, poison, polish, porter, position, powder,
power, price, print, process, produce, profit, property,
prose, protest, pull, punishment, purpose, push,
quality, question,
rain, range, rate, ray, reaction, reading, reason, record, regret, relation, religion,
representative, request, respect, rest, reward, rhythm, rice, river,
road, roll, room, rub, rule, run,
salt, sand, scale, science, sea, seat, secretary, selection, self, sense, servant, sex,
shade, shake, shame, shock, side, sign, silk, silver, sister, size, sky, sleep, slip, slope,
smash, smell, smile, smoke, sneeze, snow, soap, society, son, song, sort, sound, soup,
space, stage, start, statement, steam, steel, step, stitch, stone, stop, story, stretch,
structure, substance, sugar, suggestion, summer, support, surprise, swim, system,
talk, taste, tax, teaching, tendency, test, theory, thing, thought, thunder,
time, tin, top, touch, trade, transport, trick, trouble, turn, twist,
unit, use, value, verse, vessel, view, voice,
walk, war, wash, waste, water, wave, wax, way, weather, week, weight,
wind, wine, winter, woman, wood, wool, word, work, wound, writing,
year`,
  },
  {
    id: 'pictured',
    label: '可见事物',
    tone: '#b36b18',
    words: `angle, ant, apple, arch, arm, army,
baby, bag, ball, band, basin, basket, bath, bed, bee, bell, berry, bird,
blade, board, boat, bone, book, boot, bottle, box, boy, brain, brake,
branch, brick, bridge, brush, bucket, bulb, button,
cake, camera, card, cart, carriage, cat, chain, cheese, chest, chin,
church, circle, clock, cloud, coat, collar, comb, cord, cow, cup,
curtain, cushion,
dog, door, drain, drawer, dress, drop,
ear, egg, engine, eye,
face, farm, feather, finger, fish, flag, floor, fly, foot, fork, fowl, frame,
garden, girl, glove, goat, gun,
hair, hammer, hand, hat, head, heart, hook, horn, horse, hospital, house,
island, jewel,
kettle, key, knee, knife, knot,
leaf, leg, library, line, lip, lock,
map, match, monkey, moon, mouth, muscle,
nail, neck, needle, nerve, net, nose, nut,
office, orange, oven,
parcel, pen, pencil, picture, pig, pin, pipe, plane, plate, plough/plow,
pocket, pot, potato, prison, pump,
rail, rat, receipt, ring, rod, roof, root,
sail, school, scissors, screw, seed, sheep, shelf, ship, shirt, shoe,
skin, skirt, snake, sock, spade, sponge, spoon, spring, square, stamp,
star, station, stem, stick, stocking, stomach, store, street, sun,
table, tail, thread, throat, thumb, ticket, toe, tongue, tooth, town,
train, tray, tree, trousers,
umbrella,
wall, watch, wheel, whip, whistle, window, wing, wire, worm`,
  },
  {
    id: 'qualities',
    label: '性质',
    tone: '#44713b',
    words: `able, acid, angry, automatic, beautiful, black, boiling, bright, broken, brown,
cheap, chemical, chief, clean, clear, common, complex, conscious, cut,
deep, dependent,
early, elastic, electric, equal,
fat, fertile, first, fixed, flat, free, frequent, full,
general, good, great, grey/gray,
hanging, happy, hard, healthy, high, hollow,
important, kind,
like, living, long,
male, married, material, medical, military,
natural, necessary, new, normal,
open,
parallel, past, physical, political, poor, possible, present, private,
probable,
quick, quiet,
ready, red, regular, responsible, right, round,
same, second, separate, serious, sharp, smooth, sticky, stiff, straight,
strong, sudden, sweet,
tall, thick, tight, tired, true,
violent,
waiting, warm, wet, wide, wise,
yellow, young`,
  },
  {
    id: 'opposites',
    label: '反义性质',
    tone: '#8f4d63',
    words: `awake, bad, bent, bitter, blue, certain, cold, complete, cruel,
dark, dead, dear, delicate, different, dirty, dry,
false, feeble, female, foolish, future,
green, ill,
last, late, left, loose, loud, low,
mixed, narrow, old, opposite,
public, rough,
sad, safe, secret, short, shut, simple, slow, small, soft, solid,
special, strange,
thin, white, wrong`,
  },
];

const zh = {
  come: '来', get: '得到', give: '给', go: '去', keep: '保持', let: '让', make: '制作；使', put: '放',
  seem: '似乎', take: '拿；带', be: '是；存在', do: '做', have: '有', say: '说', see: '看见',
  send: '发送', may: '可以；可能', will: '将会', about: '关于', across: '穿过', after: '在之后',
  against: '反对；倚着', among: '在之中', before: '在之前', between: '在两者之间', down: '向下',
  from: '从', over: '在上方', through: '通过', under: '在下面', again: '再一次', enough: '足够',
  tomorrow: '明天', yesterday: '昨天', north: '北', south: '南', east: '东', west: '西', please: '请',
  yes: '是的', account: '账户；叙述', act: '行为；行动', air: '空气', animal: '动物', answer: '回答',
  art: '艺术', attack: '攻击', attention: '注意', authority: '权威', back: '背部；后面',
  balance: '平衡', base: '基础', belief: '信念', birth: '出生', blood: '血液', body: '身体',
  bread: '面包', brother: '兄弟', building: '建筑', business: '生意', care: '照顾', cause: '原因',
  change: '变化', color: '颜色', comfort: '舒适', company: '公司；陪伴', control: '控制',
  country: '国家；乡村', damage: '损害', danger: '危险', daughter: '女儿', day: '一天',
  death: '死亡', decision: '决定', design: '设计', detail: '细节', direction: '方向',
  distance: '距离', drink: '饮料；喝', earth: '地球；土地', education: '教育', effect: '影响',
  end: '结束', event: '事件', example: '例子', experience: '经验', family: '家庭', father: '父亲',
  fear: '害怕', feeling: '感觉', field: '田地；领域', fire: '火', flower: '花', food: '食物',
  friend: '朋友', fruit: '水果', glass: '玻璃；杯子', government: '政府', grass: '草',
  group: '群组', help: '帮助', history: '历史', hope: '希望', hour: '小时', idea: '想法',
  industry: '工业', interest: '兴趣；利息', journey: '旅程', knowledge: '知识', language: '语言',
  law: '法律', learning: '学习', letter: '字母；信', light: '光；轻的', list: '清单',
  love: '爱', machine: '机器', man: '男人', market: '市场', meal: '一餐', memory: '记忆',
  milk: '牛奶', money: '钱', month: '月份', mother: '母亲', mountain: '山', music: '音乐',
  name: '名字', nation: '国家', need: '需要', news: '新闻', night: '夜晚', noise: '噪音',
  number: '数字', offer: '提供', order: '顺序；命令', page: '页面', pain: '疼痛', paper: '纸',
  peace: '和平', person: '人', place: '地方', plant: '植物；种植', play: '玩；戏剧',
  point: '点；观点', power: '力量', price: '价格', process: '过程', question: '问题',
  rain: '雨', reason: '原因', record: '记录', respect: '尊重', river: '河流', road: '道路',
  room: '房间', rule: '规则', salt: '盐', school: '学校', science: '科学', sea: '海',
  sense: '感觉；意义', sister: '姐妹', size: '大小', sky: '天空', sleep: '睡眠', smile: '微笑',
  snow: '雪', society: '社会', son: '儿子', song: '歌曲', sound: '声音', space: '空间',
  start: '开始', story: '故事', summer: '夏天', system: '系统', talk: '谈话', taste: '味道',
  test: '测试', thing: '东西', thought: '想法', time: '时间', trade: '贸易', trouble: '麻烦',
  use: '使用', value: '价值', view: '视野；看法', voice: '声音', walk: '走路', war: '战争',
  water: '水', weather: '天气', week: '星期', wind: '风', winter: '冬天', woman: '女人',
  wood: '木头', word: '单词', work: '工作', writing: '写作', year: '年',
  angle: '角', apple: '苹果', arm: '手臂', baby: '婴儿', bag: '包', ball: '球', bed: '床',
  bird: '鸟', book: '书', bottle: '瓶子', boy: '男孩', brain: '大脑', bridge: '桥',
  camera: '相机', card: '卡片', cat: '猫', chain: '链条', clock: '钟', cloud: '云',
  coat: '外套', cow: '奶牛', cup: '杯子', dog: '狗', door: '门', ear: '耳朵', egg: '蛋',
  eye: '眼睛', face: '脸', farm: '农场', finger: '手指', fish: '鱼', floor: '地板',
  foot: '脚', garden: '花园', girl: '女孩', hair: '头发', hand: '手', hat: '帽子',
  head: '头', heart: '心', horse: '马', house: '房子', island: '岛', key: '钥匙',
  knee: '膝盖', knife: '刀', leaf: '叶子', leg: '腿', library: '图书馆', line: '线',
  map: '地图', moon: '月亮', mouth: '嘴', neck: '脖子', nose: '鼻子', office: '办公室',
  orange: '橙子；橙色', pen: '钢笔', pencil: '铅笔', picture: '图片', plate: '盘子',
  pocket: '口袋', potato: '土豆', prison: '监狱', ring: '戒指', roof: '屋顶',
  seed: '种子', sheep: '羊', shirt: '衬衫', shoe: '鞋', skin: '皮肤', snake: '蛇',
  spoon: '勺子', spring: '春天；弹簧', star: '星星', street: '街道', sun: '太阳',
  table: '桌子', tooth: '牙齿', town: '城镇', train: '火车', tree: '树', umbrella: '伞',
  wall: '墙', watch: '手表；看', wheel: '轮子', window: '窗户', wing: '翅膀',
  able: '能够的', acid: '酸的', angry: '生气的', automatic: '自动的', beautiful: '美丽的',
  black: '黑色的', bright: '明亮的', broken: '破损的', brown: '棕色的', cheap: '便宜的',
  clean: '干净的', clear: '清楚的', common: '常见的', deep: '深的', early: '早的',
  equal: '相等的', fat: '胖的；脂肪', first: '第一的', flat: '平的', free: '自由的；免费的',
  full: '满的', good: '好的', great: '伟大的', happy: '快乐的', hard: '困难的；硬的',
  healthy: '健康的', high: '高的', important: '重要的', kind: '友善的；种类',
  living: '活着的', long: '长的', natural: '自然的', necessary: '必要的', new: '新的',
  open: '打开的', poor: '贫穷的；差的', possible: '可能的', present: '现在的；礼物',
  quick: '快的', quiet: '安静的', ready: '准备好的', red: '红色的', right: '正确的；右边',
  round: '圆的', serious: '严肃的', sharp: '锋利的', smooth: '光滑的', strong: '强壮的',
  sweet: '甜的', tall: '高的', tired: '疲惫的', true: '真实的', warm: '温暖的',
  wet: '湿的', wide: '宽的', wise: '明智的', yellow: '黄色的', young: '年轻的',
  awake: '醒着的', bad: '坏的', bitter: '苦的', blue: '蓝色的', cold: '冷的',
  dark: '黑暗的', dead: '死的', different: '不同的', dirty: '脏的', dry: '干的',
  false: '错误的', female: '女性的', foolish: '愚蠢的', future: '未来的', green: '绿色的',
  late: '迟的', left: '左边', loud: '大声的', low: '低的', narrow: '窄的',
  old: '老的；旧的', public: '公共的', rough: '粗糙的', sad: '悲伤的', safe: '安全的',
  secret: '秘密的', short: '短的', shut: '关闭的', simple: '简单的', slow: '慢的',
  small: '小的', soft: '软的', thin: '薄的；瘦的', white: '白色的', wrong: '错误的',
};

const ipa = {
  "come": "/k??m/",
  "get": "/??et/",
  "give": "/???v/",
  "go": "/??o?/",
  "keep": "/k?i?p/",
  "let": "/l?et/",
  "make": "/m?e?k/",
  "put": "/p??t/",
  "seem": "/s?i?m/",
  "take": "/t?e?k/",
  "be": "/b?i?/",
  "do": "/d?u?/",
  "have": "/h??v/",
  "say": "/s?e?/",
  "see": "/s?i?/",
  "send": "/s?end/",
  "may": "/me?/",
  "will": "/w?l/",
  "about": "/?b?a?t/",
  "across": "/?kr??s/",
  "after": "/??ft?/",
  "against": "/???enst/",
  "among": "/?m???/",
  "at": "/??t/",
  "before": "/b?f??r/",
  "between": "/b?tw?i?n/",
  "by": "/b?a?/",
  "down": "/d?a?n/",
  "from": "/fr??m/",
  "in": "/?n/",
  "off": "/??f/",
  "on": "/??n/",
  "over": "/?o?v?/",
  "through": "/?r?u?/",
  "to": "/t?u?/",
  "under": "/??nd?/",
  "up": "/??p/",
  "with": "/w???/",
  "as": "/??z/",
  "for": "/f??r/",
  "of": "/??v/",
  "till": "/t??l/",
  "than": "/???n/",
  "a": "/?/",
  "the": "/??/",
  "all": "/??l/",
  "any": "/?eni?/",
  "every": "/?ev?i?/",
  "little": "/l??t?l/",
  "much": "/m??t?/",
  "no": "/n?o?/",
  "other": "/????/",
  "some": "/s??m/",
  "such": "/s??t?/",
  "that": "/???t/",
  "this": "/???s/",
  "I": "/a?/",
  "he": "/h?i?/",
  "you": "/j?u?/",
  "who": "/hu?/",
  "and": "/?nd/",
  "because": "/b?k??z/",
  "but": "/b??t/",
  "or": "/??r/",
  "if": "/??f/",
  "though": "/??o?/",
  "while": "/w?a?l/",
  "how": "/h?a?/",
  "when": "/w?en/",
  "where": "/w?er/",
  "why": "/w?a?/",
  "again": "/???en/",
  "ever": "/?ev?/",
  "far": "/f??r/",
  "forward": "/f??rw?d/",
  "here": "/h?i?r/",
  "near": "/n??r/",
  "now": "/n?a?/",
  "out": "/?a?t/",
  "still": "/st??l/",
  "then": "/??en/",
  "there": "/??er/",
  "together": "/t???e??/",
  "well": "/w?el/",
  "almost": "/??lm?o?st/",
  "enough": "/?n??f/",
  "even": "/?i?v?n/",
  "not": "/n??t/",
  "only": "/?o?nli?/",
  "quite": "/kw?a?t/",
  "so": "/s?o?/",
  "very": "/v?eri?/",
  "tomorrow": "/t?m??r?o?/",
  "yesterday": "/j?est?d?e?/",
  "north": "/n??r?/",
  "south": "/s?a??/",
  "east": "/?i?st/",
  "west": "/w?est/",
  "please": "/pl?i?z/",
  "yes": "/jes/",
  "account": "/?k?a?nt/",
  "act": "/??kt/",
  "addition": "/?d????n/",
  "adjustment": "/?d???stm?nt/",
  "advertisement": "/?dv??t?zm?nt/",
  "agreement": "/??r?i?m?nt/",
  "air": "/?er/",
  "amount": "/?m?a?nt/",
  "amusement": "/?mj?u?zm?nt/",
  "animal": "/??n?m?l/",
  "answer": "/??ns?/",
  "apparatus": "/??p???t?s/",
  "approval": "/?pr?u?v?l/",
  "argument": "/??r?j?m?nt/",
  "art": "/??rt/",
  "attack": "/?t??k/",
  "attempt": "/?t?empt/",
  "attention": "/?t?en??n/",
  "attraction": "/?tr??k??n/",
  "authority": "/????r?ti?/",
  "back": "/b??k/",
  "balance": "/b??l?ns/",
  "base": "/b?e?s/",
  "behavior": "/b?h?e?vj?/",
  "belief": "/b?l?i?f/",
  "birth": "/b???/",
  "bit": "/b??t/",
  "bite": "/b?a?t/",
  "blood": "/bl??d/",
  "blow": "/bl?o?/",
  "body": "/b??di?/",
  "brass": "/br??s/",
  "bread": "/br?ed/",
  "breath": "/br?e?/",
  "brother": "/br????/",
  "building": "/b??ld??/",
  "burn": "/b??n/",
  "burst": "/b??st/",
  "business": "/b??zn?s/",
  "butter": "/b??t?/",
  "canvas": "/k??nv?s/",
  "care": "/k?er/",
  "cause": "/k??z/",
  "chalk": "/t???k/",
  "chance": "/t???ns/",
  "change": "/t??e?nd?/",
  "cloth": "/kl???/",
  "coal": "/k?o?l/",
  "color": "/k??l?/",
  "comfort": "/k??mf?t/",
  "committee": "/k?m??ti?/",
  "company": "/k??mp?n?i?/",
  "comparison": "/k?mp?er?s?n/",
  "competition": "/k??mp?t????n/",
  "condition": "/k?nd????n/",
  "connection": "/k?n?ek??n/",
  "control": "/k?ntr?o?l/",
  "cook": "/k??k/",
  "copper": "/k??p?/",
  "copy": "/k??pi?/",
  "cork": "/k??rk/",
  "cotton": "/k??t?n/",
  "cough": "/k??f/",
  "country": "/k??ntri?/",
  "cover": "/k??v?/",
  "crack": "/kr??k/",
  "credit": "/kr?ed?t/",
  "crime": "/kr?a?m/",
  "crush": "/kr???/",
  "cry": "/kr?a?/",
  "current": "/k???nt/",
  "curve": "/k??v/",
  "damage": "/d??m?d?/",
  "danger": "/d?e?nd??/",
  "daughter": "/d??t?/",
  "day": "/d?e?/",
  "death": "/d?e?/",
  "debt": "/d?et/",
  "decision": "/d?s????n/",
  "degree": "/d??r?i?/",
  "design": "/d?z?a?n/",
  "desire": "/d?z?a??/",
  "destruction": "/d?str??k??n/",
  "detail": "/d?t?e?l/",
  "development": "/d?v?el?pm?nt/",
  "digestion": "/da?d??est??n/",
  "direction": "/d??ek??n/",
  "discovery": "/d?sk??v?i?/",
  "discussion": "/d?sk????n/",
  "disease": "/d?z?i?z/",
  "disgust": "/d?s???st/",
  "distance": "/d??st?ns/",
  "distribution": "/d??str?bj?u???n/",
  "division": "/d?v????n/",
  "doubt": "/d?a?t/",
  "drink": "/dr???k/",
  "driving": "/dr?a?v??/",
  "dust": "/d??st/",
  "earth": "/???/",
  "edge": "/?ed?/",
  "education": "/?ed??k?e???n/",
  "effect": "/?f?ekt/",
  "end": "/?end/",
  "error": "/?er?/",
  "event": "/?v?ent/",
  "example": "/??z??mp?l/",
  "exchange": "/?kst??e?nd?/",
  "existence": "/e?z??st?ns/",
  "expansion": "/?ksp??n??n/",
  "experience": "/?ksp??ri??ns/",
  "expert": "/?eksp?t/",
  "fact": "/f??kt/",
  "fall": "/f??l/",
  "family": "/f??m?li?/",
  "father": "/f????/",
  "fear": "/f??r/",
  "feeling": "/f?i?l??/",
  "fiction": "/f??k??n/",
  "field": "/f?i?ld/",
  "fight": "/f?a?t/",
  "fire": "/f?a??/",
  "flame": "/fl?e?m/",
  "flight": "/fl?a?t/",
  "flower": "/fl?a??/",
  "fold": "/f?o?ld/",
  "food": "/f?u?d/",
  "force": "/f??rs/",
  "form": "/f??rm/",
  "friend": "/fr?end/",
  "front": "/fr??nt/",
  "fruit": "/fr?u?t/",
  "glass": "/?l??s/",
  "gold": "/??o?ld/",
  "government": "/???v?m?nt/",
  "grain": "/?r?e?n/",
  "grass": "/?r??s/",
  "grip": "/?r??p/",
  "group": "/?r?u?p/",
  "growth": "/?r?o??/",
  "guide": "/??a?d/",
  "harbor": "/h??rb?/",
  "harmony": "/h??rm?ni?/",
  "hate": "/h?e?t/",
  "hearing": "/h?i?r??/",
  "heat": "/h?i?t/",
  "help": "/h?elp/",
  "history": "/h??st?i?/",
  "hole": "/h?o?l/",
  "hope": "/h?o?p/",
  "hour": "/?a??/",
  "humor": "/hj?u?m?/",
  "ice": "/?a?s/",
  "idea": "/a?d?i??/",
  "impulse": "/??mp?ls/",
  "increase": "/??nkr?i?s/",
  "industry": "/??nd?stri?/",
  "ink": "/???k/",
  "insect": "/??ns?ekt/",
  "instrument": "/??nstr?m?nt/",
  "insurance": "/??n???r?ns/",
  "interest": "/??ntr?st/",
  "invention": "/??nv?en??n/",
  "iron": "/?a??n/",
  "jelly": "/d??eli?/",
  "join": "/d????n/",
  "journey": "/d???ni?/",
  "judge": "/d???d?/",
  "jump": "/d???mp/",
  "kick": "/k??k/",
  "kiss": "/k??s/",
  "knowledge": "/n??l?d?/",
  "land": "/l??nd/",
  "language": "/l????w?d?/",
  "laugh": "/l??f/",
  "law": "/l??/",
  "lead": "/l?ed/",
  "learning": "/l??n??/",
  "leather": "/l?e??/",
  "letter": "/l?et?/",
  "level": "/l?ev?l/",
  "lift": "/l??ft/",
  "light": "/l?a?t/",
  "limit": "/l??m?t/",
  "linen": "/l??n?n/",
  "liquid": "/l??kw?d/",
  "list": "/l??st/",
  "look": "/l??k/",
  "loss": "/l??s/",
  "love": "/l??v/",
  "machine": "/m???i?n/",
  "man": "/m??n/",
  "manager": "/m??n?d??/",
  "mark": "/m??rk/",
  "market": "/m??rk?t/",
  "mass": "/m??s/",
  "meal": "/m?i?l/",
  "measure": "/m?e??/",
  "meat": "/m?i?t/",
  "meeting": "/m?i?t??/",
  "memory": "/m?em?i?/",
  "metal": "/m?et?l/",
  "middle": "/m??d?l/",
  "milk": "/m??lk/",
  "mind": "/m?a?nd/",
  "mine": "/m?a?n/",
  "minute": "/m??n?t/",
  "mist": "/m??st/",
  "money": "/m??ni?/",
  "month": "/m??n?/",
  "morning": "/m??rn??/",
  "mother": "/m????/",
  "motion": "/m?o???n/",
  "mountain": "/m?a?nt?n/",
  "move": "/m?u?v/",
  "music": "/mj?u?z?k/",
  "name": "/n?e?m/",
  "nation": "/n?e???n/",
  "need": "/n?i?d/",
  "news": "/n?u?z/",
  "night": "/n?a?t/",
  "noise": "/n???z/",
  "note": "/n?o?t/",
  "number": "/n??mb?/",
  "observation": "/??bz?v?e???n/",
  "offer": "/??f?/",
  "oil": "/???l/",
  "operation": "/??p??e???n/",
  "opinion": "/?p??nj?n/",
  "order": "/??rd?/",
  "organization": "/??r??n?z?e???n/",
  "ornament": "/??rn?m?nt/",
  "owner": "/?o?n?/",
  "page": "/p?e?d?/",
  "pain": "/p?e?n/",
  "paint": "/p?e?nt/",
  "paper": "/p?e?p?/",
  "part": "/p??rt/",
  "paste": "/p?e?st/",
  "payment": "/p?e?m?nt/",
  "peace": "/p?i?s/",
  "person": "/p??s?n/",
  "place": "/pl?e?s/",
  "plant": "/pl??nt/",
  "play": "/pl?e?/",
  "pleasure": "/pl?e??/",
  "point": "/p???nt/",
  "poison": "/p???z?n/",
  "polish": "/p??l??/",
  "porter": "/p??rt?/",
  "position": "/p?z????n/",
  "powder": "/p?a?d?/",
  "power": "/p?a??/",
  "price": "/pr?a?s/",
  "print": "/pr??nt/",
  "process": "/pr??s?es/",
  "produce": "/pr?d?u?s/",
  "profit": "/pr??f?t/",
  "property": "/pr??p?ti?/",
  "prose": "/pr?o?z/",
  "protest": "/pr?o?t?est/",
  "pull": "/p??l/",
  "punishment": "/p??n??m?nt/",
  "purpose": "/p??p?s/",
  "push": "/p???/",
  "quality": "/kw??l?ti?/",
  "question": "/kw?est??n/",
  "rain": "/r?e?n/",
  "range": "/r?e?nd?/",
  "rate": "/r?e?t/",
  "ray": "/r?e?/",
  "reaction": "/ri???k??n/",
  "reading": "/r?i?d??/",
  "reason": "/r?i?z?n/",
  "record": "/r?k??rd/",
  "regret": "/r??r?et/",
  "relation": "/ri?l?e???n/",
  "religion": "/r?l??d??n/",
  "representative": "/r?epr?z?ent?t?v/",
  "request": "/r?kw?est/",
  "respect": "/r?sp?ekt/",
  "rest": "/r?est/",
  "reward": "/r?w??rd/",
  "rhythm": "/r????m/",
  "rice": "/r?a?s/",
  "river": "/r??v?/",
  "road": "/r?o?d/",
  "roll": "/r?o?l/",
  "room": "/r?u?m/",
  "rub": "/r??b/",
  "rule": "/r?u?l/",
  "run": "/r??n/",
  "salt": "/s??lt/",
  "sand": "/s??nd/",
  "scale": "/sk?e?l/",
  "science": "/s?a??ns/",
  "sea": "/s?i?/",
  "seat": "/s?i?t/",
  "secretary": "/s?ekr?t?eri?/",
  "selection": "/s?l?ek??n/",
  "self": "/s?elf/",
  "sense": "/s?ens/",
  "servant": "/s??v?nt/",
  "sex": "/s?eks/",
  "shade": "/??e?d/",
  "shake": "/??e?k/",
  "shame": "/??e?m/",
  "shock": "/???k/",
  "side": "/s?a?d/",
  "sign": "/s?a?n/",
  "silk": "/s??lk/",
  "silver": "/s??lv?/",
  "sister": "/s??st?/",
  "size": "/s?a?z/",
  "sky": "/sk?a?/",
  "sleep": "/sl?i?p/",
  "slip": "/sl??p/",
  "slope": "/sl?o?p/",
  "smash": "/sm???/",
  "smell": "/sm?el/",
  "smile": "/sm?a?l/",
  "smoke": "/sm?o?k/",
  "sneeze": "/sn?i?z/",
  "snow": "/sn?o?/",
  "soap": "/s?o?p/",
  "society": "/s?s?a??ti?/",
  "son": "/s??n/",
  "song": "/s???/",
  "sort": "/s??rt/",
  "sound": "/s?a?nd/",
  "soup": "/s?u?p/",
  "space": "/sp?e?s/",
  "stage": "/st?e?d?/",
  "start": "/st??rt/",
  "statement": "/st?e?tm?nt/",
  "steam": "/st?i?m/",
  "steel": "/st?i?l/",
  "step": "/st?ep/",
  "stitch": "/st??t?/",
  "stone": "/st?o?n/",
  "stop": "/st??p/",
  "story": "/st??ri?/",
  "stretch": "/str?et?/",
  "structure": "/str??kt??/",
  "substance": "/s??bst?ns/",
  "sugar": "/?????/",
  "suggestion": "/s?d??est??n/",
  "summer": "/s??m?/",
  "support": "/s?p??rt/",
  "surprise": "/s?pr?a?z/",
  "swim": "/sw??m/",
  "system": "/s??st?m/",
  "talk": "/t??k/",
  "taste": "/t?e?st/",
  "tax": "/t??ks/",
  "teaching": "/t?i?t???/",
  "tendency": "/t?end?nsi?/",
  "test": "/t?est/",
  "theory": "/???ri?/",
  "thing": "/????/",
  "thought": "/???t/",
  "thunder": "/???nd?/",
  "time": "/t?a?m/",
  "tin": "/t??n/",
  "top": "/t??p/",
  "touch": "/t??t?/",
  "trade": "/tr?e?d/",
  "transport": "/tr?nsp??rt/",
  "trick": "/tr??k/",
  "trouble": "/tr??b?l/",
  "turn": "/t??n/",
  "twist": "/tw??st/",
  "unit": "/j?u?n?t/",
  "use": "/j?u?s/",
  "value": "/v??lju?/",
  "verse": "/v??s/",
  "vessel": "/v?es?l/",
  "view": "/vj?u?/",
  "voice": "/v???s/",
  "walk": "/w??k/",
  "war": "/w??r/",
  "wash": "/w???/",
  "waste": "/w?e?st/",
  "water": "/w??t?/",
  "wave": "/w?e?v/",
  "wax": "/w??ks/",
  "way": "/w?e?/",
  "weather": "/w?e??/",
  "week": "/w?i?k/",
  "weight": "/w?e?t/",
  "wind": "/w?a?nd/",
  "wine": "/w?a?n/",
  "winter": "/w??nt?/",
  "woman": "/w??m?n/",
  "wood": "/w??d/",
  "wool": "/w??l/",
  "word": "/w??d/",
  "work": "/w??k/",
  "wound": "/w?a?nd/",
  "writing": "/r?a?t??/",
  "year": "/j??r/",
  "angle": "/?????l/",
  "ant": "/??nt/",
  "apple": "/??p?l/",
  "arch": "/??rt?/",
  "arm": "/??rm/",
  "army": "/??rmi?/",
  "baby": "/b?e?bi?/",
  "bag": "/b???/",
  "ball": "/b??l/",
  "band": "/b??nd/",
  "basin": "/b?e?s?n/",
  "basket": "/b??sk?t/",
  "bath": "/b???/",
  "bed": "/b?ed/",
  "bee": "/b?i?/",
  "bell": "/b?el/",
  "berry": "/b?eri?/",
  "bird": "/b??d/",
  "blade": "/bl?e?d/",
  "board": "/b??rd/",
  "boat": "/b?o?t/",
  "bone": "/b?o?n/",
  "book": "/b??k/",
  "boot": "/b?u?t/",
  "bottle": "/b??t?l/",
  "box": "/b??ks/",
  "boy": "/b???/",
  "brain": "/br?e?n/",
  "brake": "/br?e?k/",
  "branch": "/br??nt?/",
  "brick": "/br??k/",
  "bridge": "/br??d?/",
  "brush": "/br???/",
  "bucket": "/b??k?t/",
  "bulb": "/b??lb/",
  "button": "/b??t?n/",
  "cake": "/k?e?k/",
  "camera": "/k??m??/",
  "card": "/k??rd/",
  "cart": "/k??rt/",
  "carriage": "/k??r?d?/",
  "cat": "/k??t/",
  "chain": "/t??e?n/",
  "cheese": "/t??i?z/",
  "chest": "/t??est/",
  "chin": "/t???n/",
  "church": "/t???t?/",
  "circle": "/s??k?l/",
  "clock": "/kl??k/",
  "cloud": "/kl?a?d/",
  "coat": "/k?o?t/",
  "collar": "/k??l?/",
  "comb": "/k?o?m/",
  "cord": "/k??rd/",
  "cow": "/k?a?/",
  "cup": "/k??p/",
  "curtain": "/k??t?n/",
  "cushion": "/k????n/",
  "dog": "/d???/",
  "door": "/d??r/",
  "drain": "/dr?e?n/",
  "drawer": "/dr??r/",
  "dress": "/dr?es/",
  "drop": "/dr??p/",
  "ear": "/?i?r/",
  "egg": "/?e?/",
  "engine": "/?end??n/",
  "eye": "/?a?/",
  "face": "/f?e?s/",
  "farm": "/f??rm/",
  "feather": "/f?e??/",
  "finger": "/f?????/",
  "fish": "/f???/",
  "flag": "/fl???/",
  "floor": "/fl??r/",
  "fly": "/fl?a?/",
  "foot": "/f??t/",
  "fork": "/f??rk/",
  "fowl": "/fa?l/",
  "frame": "/fr?e?m/",
  "garden": "/???rd?n/",
  "girl": "/???l/",
  "glove": "/?l??v/",
  "goat": "/??o?t/",
  "gun": "/???n/",
  "hair": "/h?er/",
  "hammer": "/h??m?/",
  "hand": "/h??nd/",
  "hat": "/h??t/",
  "head": "/h?ed/",
  "heart": "/h??rt/",
  "hook": "/h??k/",
  "horn": "/h??rn/",
  "horse": "/h??rs/",
  "hospital": "/h??sp??t?l/",
  "house": "/h?a?s/",
  "island": "/?a?l?nd/",
  "jewel": "/d??u??l/",
  "kettle": "/k?et?l/",
  "key": "/k?i?/",
  "knee": "/n?i?/",
  "knife": "/n?a?f/",
  "knot": "/n??t/",
  "leaf": "/l?i?f/",
  "leg": "/l?e?/",
  "library": "/l?a?brer?i?/",
  "line": "/l?a?n/",
  "lip": "/l??p/",
  "lock": "/l??k/",
  "map": "/m??p/",
  "match": "/m??t?/",
  "monkey": "/m???ki?/",
  "moon": "/m?u?n/",
  "mouth": "/m?a??/",
  "muscle": "/m??s?l/",
  "nail": "/n?e?l/",
  "neck": "/n?ek/",
  "needle": "/n?i?d?l/",
  "nerve": "/n??v/",
  "net": "/n?et/",
  "nose": "/n?o?z/",
  "nut": "/n??t/",
  "office": "/??f?s/",
  "orange": "/??r?nd?/",
  "oven": "/??v?n/",
  "parcel": "/p??rs?l/",
  "pen": "/p?en/",
  "pencil": "/p?ens?l/",
  "picture": "/p??kt??/",
  "pig": "/p???/",
  "pin": "/p??n/",
  "pipe": "/p?a?p/",
  "plane": "/pl?e?n/",
  "plate": "/pl?e?t/",
  "plough": "/pla?/",
  "pocket": "/p??k?t/",
  "pot": "/p??t/",
  "potato": "/p?t?e?t?o?/",
  "prison": "/pr??z?n/",
  "pump": "/p??mp/",
  "rail": "/r?e?l/",
  "rat": "/r??t/",
  "receipt": "/r?s?i?t/",
  "ring": "/r???/",
  "rod": "/r??d/",
  "roof": "/r?u?f/",
  "root": "/r?u?t/",
  "sail": "/s?e?l/",
  "school": "/sk?u?l/",
  "scissors": "/s??z?z/",
  "screw": "/skr?u?/",
  "seed": "/s?i?d/",
  "sheep": "/??i?p/",
  "shelf": "/??elf/",
  "ship": "/???p/",
  "shirt": "/???t/",
  "shoe": "/??u?/",
  "skin": "/sk??n/",
  "skirt": "/sk??t/",
  "snake": "/sn?e?k/",
  "sock": "/s??k/",
  "spade": "/sp?e?d/",
  "sponge": "/sp??nd?/",
  "spoon": "/sp?u?n/",
  "spring": "/spr???/",
  "square": "/skw?er/",
  "stamp": "/st??mp/",
  "star": "/st??r/",
  "station": "/st?e???n/",
  "stem": "/st?em/",
  "stick": "/st??k/",
  "stocking": "/st??k??/",
  "stomach": "/st??m?k/",
  "store": "/st??r/",
  "street": "/str?i?t/",
  "sun": "/s??n/",
  "table": "/t?e?b?l/",
  "tail": "/t?e?l/",
  "thread": "/?r?ed/",
  "throat": "/?r?o?t/",
  "thumb": "/???m/",
  "ticket": "/t??k?t/",
  "toe": "/t?o?/",
  "tongue": "/t???/",
  "tooth": "/t?u??/",
  "town": "/t?a?n/",
  "train": "/tr?e?n/",
  "tray": "/tr?e?/",
  "tree": "/tr?i?/",
  "trousers": "/tr?a?z?z/",
  "umbrella": "/?mbr?el?/",
  "wall": "/w??l/",
  "watch": "/w??t?/",
  "wheel": "/w?i?l/",
  "whip": "/w??p/",
  "whistle": "/w??s?l/",
  "window": "/w??ndo?/",
  "wing": "/w???/",
  "wire": "/w?a??/",
  "worm": "/w??m/",
  "able": "/?e?b?l/",
  "acid": "/??s?d/",
  "angry": "/????ri?/",
  "automatic": "/??t?m??t?k/",
  "beautiful": "/bj?u?t?f?l/",
  "black": "/bl??k/",
  "boiling": "/b???l??/",
  "bright": "/br?a?t/",
  "broken": "/br?o?k?n/",
  "brown": "/br?a?n/",
  "cheap": "/t??i?p/",
  "chemical": "/k?em?k?l/",
  "chief": "/t??i?f/",
  "clean": "/kl?i?n/",
  "clear": "/kl??r/",
  "common": "/k??m?n/",
  "complex": "/k??mpleks/",
  "conscious": "/k??n??s/",
  "cut": "/k??t/",
  "deep": "/d?i?p/",
  "dependent": "/d?p?end?nt/",
  "early": "/??li?/",
  "elastic": "/?l??st?k/",
  "electric": "/?l?ektr?k/",
  "equal": "/?i?kw?l/",
  "fat": "/f??t/",
  "fertile": "/f??t?l/",
  "first": "/f??st/",
  "fixed": "/f??kst/",
  "flat": "/fl??t/",
  "free": "/fr?i?/",
  "frequent": "/fr?i?kw?nt/",
  "full": "/f??l/",
  "general": "/d??en??l/",
  "good": "/???d/",
  "great": "/?r?e?t/",
  "grey": "/?re?/",
  "hanging": "/h?????/",
  "happy": "/h??pi?/",
  "hard": "/h??rd/",
  "healthy": "/h?el?i?/",
  "high": "/h?a?/",
  "hollow": "/h??lo?/",
  "important": "/??mp??rt?nt/",
  "kind": "/k?a?nd/",
  "like": "/l?a?k/",
  "living": "/l??v??/",
  "long": "/l???/",
  "male": "/m?e?l/",
  "married": "/m?eri?d/",
  "material": "/m?t??ri??l/",
  "medical": "/m?ed?k?l/",
  "military": "/m??l?t?eri?/",
  "natural": "/n??t???l/",
  "necessary": "/n?es?s?eri?/",
  "new": "/n?u?/",
  "normal": "/n??rm?l/",
  "open": "/?o?p?n/",
  "parallel": "/p?er?l?el/",
  "past": "/p??st/",
  "physical": "/f??z?k?l/",
  "political": "/p?l??t?k?l/",
  "poor": "/p?u?r/",
  "possible": "/p??s?b?l/",
  "present": "/pr?ez?nt/",
  "private": "/pr?a?v?t/",
  "probable": "/pr??b?b?l/",
  "quick": "/kw??k/",
  "quiet": "/kw?a??t/",
  "ready": "/r?edi?/",
  "red": "/r?ed/",
  "regular": "/r?e?j?l?/",
  "responsible": "/ri?sp??ns?b?l/",
  "right": "/r?a?t/",
  "round": "/r?a?nd/",
  "same": "/s?e?m/",
  "second": "/s?ek?nd/",
  "separate": "/s?ep??e?t/",
  "serious": "/s??ri??s/",
  "sharp": "/???rp/",
  "smooth": "/sm?u??/",
  "sticky": "/st??ki?/",
  "stiff": "/st??f/",
  "straight": "/str?e?t/",
  "strong": "/str???/",
  "sudden": "/s??d?n/",
  "sweet": "/sw?i?t/",
  "tall": "/t??l/",
  "thick": "/???k/",
  "tight": "/t?a?t/",
  "tired": "/t?a??d/",
  "true": "/tr?u?/",
  "violent": "/v?a??l?nt/",
  "waiting": "/w?e?t??/",
  "warm": "/w??rm/",
  "wet": "/w?et/",
  "wide": "/w?a?d/",
  "wise": "/w?a?z/",
  "yellow": "/j?elo?/",
  "young": "/j???/",
  "awake": "/?w?e?k/",
  "bad": "/b??d/",
  "bent": "/b?ent/",
  "bitter": "/b??t?/",
  "blue": "/bl?u?/",
  "certain": "/s??t?n/",
  "cold": "/k?o?ld/",
  "complete": "/k?mpl?i?t/",
  "cruel": "/kr?u??l/",
  "dark": "/d??rk/",
  "dead": "/d?ed/",
  "dear": "/d??r/",
  "delicate": "/d?el?k?t/",
  "different": "/d??f??nt/",
  "dirty": "/d??ti?/",
  "dry": "/dr?a?/",
  "false": "/f??ls/",
  "feeble": "/f?i?b?l/",
  "female": "/f?i?m?e?l/",
  "foolish": "/f?u?l??/",
  "future": "/fj?u?t??/",
  "green": "/?r?i?n/",
  "ill": "/??l/",
  "last": "/l??st/",
  "late": "/l?e?t/",
  "left": "/l?eft/",
  "loose": "/l?u?s/",
  "loud": "/l?a?d/",
  "low": "/l?o?/",
  "mixed": "/m??kst/",
  "narrow": "/n?ero?/",
  "old": "/?o?ld/",
  "opposite": "/??p?z?t/",
  "public": "/p??bl?k/",
  "rough": "/r??f/",
  "sad": "/s??d/",
  "safe": "/s?e?f/",
  "secret": "/s?i?kr?t/",
  "short": "/???rt/",
  "shut": "/???t/",
  "simple": "/s??mp?l/",
  "slow": "/sl?o?/",
  "small": "/sm??l/",
  "soft": "/s??ft/",
  "solid": "/s??l?d/",
  "special": "/sp?e??l/",
  "strange": "/str?e?nd?/",
  "thin": "/???n/",
  "white": "/w?a?t/",
  "wrong": "/r???/",
};

const cleanToken = (word) => word.trim().replace(/\s+/g, ' ').replace(/[.。]/g, '');

export const groups = rawGroups.map((group) => ({
  ...group,
  count: group.words.split(',').map(cleanToken).filter(Boolean).length,
}));

export const words = rawGroups.flatMap((group) =>
  group.words
    .split(',')
    .map(cleanToken)
    .filter(Boolean)
    .map((word, index) => {
      const speakWord = word.includes('/') ? word.split('/')[0].trim() : word;
      return {
        id: `${group.id}-${index}-${speakWord.toLowerCase()}`,
        word,
        speakWord,
        groupId: group.id,
        groupLabel: group.label,
        tone: group.tone,
        zh: zh[speakWord] || `${group.label}词`,
        ipa: ipa[speakWord] || '',
      };
    }),
);
