const rawGroups = [
  {
    id: 'operations',
    label: '操作词',
    tone: '#1f8a5b',
    words: `come, get, give, go, keep, let, make, put, seem, take,
be, do, have, say, see, send, may, will,
about, across, after, against, among, at, before, between, by,
down, from, in, off, on, over, through, to, under, up, with,
as, for, of, till, than,
a, the, all, any, every, little, much, no, other, some, such, that, this,
I, he, you, who,
and, because, but, or, if, though, while, how, when, where, why,
again, ever, far, forward, here, near, now, out, still, then,
there, together, well,
almost, enough, even, not, only, quite, so, very,
tomorrow, yesterday,
north, south, east, west, please, yes`,
  },
  {
    id: 'things',
    label: '一般事物',
    tone: '#2e6f9f',
    words: `account, act, addition, adjustment, advertisement, agreement, air,
amount, amusement, animal, answer, apparatus, approval, argument, art,
attack, attempt, attention, attraction, authority,
back, balance, base, behavior, belief, birth, bit, bite, blood, blow,
body, brass, bread, breath, brother, building, burn, burst, business,
butter,
canvas, care, cause, chalk, chance, change, cloth, coal, color, comfort,
committee, company, comparison, competition, condition, connection,
control, cook, copper, copy, cork, cotton, cough, country, cover,
crack, credit, crime, crush, cry, current, curve,
damage, danger, daughter, day, death, debt, decision, degree, design,
desire, destruction, detail, development, digestion, direction,
discovery, discussion, disease, disgust, distance,
distribution, division, doubt, drink, driving, dust,
earth, edge, education, effect, end, error, event, example, exchange,
existence, expansion, experience, expert,
fact, fall, family, father, fear, feeling, fiction, field, fight, fire,
flame, flight, flower, fold, food, force, form, friend, front, fruit,
glass, gold, government, grain, grass, grip, group, growth, guide,
harbor, harmony, hate, hearing, heat, help, history, hole, hope, hour, humor,
ice, idea, impulse, increase, industry, ink, insect, instrument,
insurance, interest, invention, iron,
jelly, join, journey, judge, jump,
kick, kiss, knowledge,
land, language, laugh, law, lead, learning, leather, letter, level,
lift, light, limit, linen, liquid, list, look, loss, love,
machine, man, manager, mark, market, mass, meal, measure, meat, meeting,
memory, metal, middle, milk, mind, mine, minute, mist, money, month,
morning, mother, motion, mountain, move, music,
name, nation, need, news, night, noise, note, number,
observation, offer, oil, operation, opinion, order, organization,
ornament, owner,
page, pain, paint, paper, part, paste, payment, peace, person, place,
plant, play, pleasure, point, poison, polish, porter, position, powder,
power, price, print, process, produce, profit, property,
prose, protest, pull, punishment, purpose, push,
quality, question,
rain, range, rate, ray, reaction, reading, reason, record, regret, relation, religion,
representative, request, respect, rest, reward, rhythm, rice, river,
road, roll, room, rub, rule, run,
salt, sand, scale, science, sea, seat, secretary, selection, self, sense, servant, sex,
shade, shake, shame, shock, side, sign, silk, silver, sister, size, sky, sleep, slip, slope,
smash, smell, smile, smoke, sneeze, snow, soap, society, son, song, sort, sound, soup,
space, stage, start, statement, steam, steel, step, stitch, stone, stop, story, stretch,
structure, substance, sugar, suggestion, summer, support, surprise, swim, system,
talk, taste, tax, teaching, tendency, test, theory, thing, thought, thunder,
time, tin, top, touch, trade, transport, trick, trouble, turn, twist,
unit, use, value, verse, vessel, view, voice,
walk, war, wash, waste, water, wave, wax, way, weather, week, weight,
wind, wine, winter, woman, wood, wool, word, work, wound, writing,
year`,
  },
  {
    id: 'pictured',
    label: '可见事物',
    tone: '#b36b18',
    words: `angle, ant, apple, arch, arm, army,
baby, bag, ball, band, basin, basket, bath, bed, bee, bell, berry, bird,
blade, board, boat, bone, book, boot, bottle, box, boy, brain, brake,
branch, brick, bridge, brush, bucket, bulb, button,
cake, camera, card, cart, carriage, cat, chain, cheese, chest, chin,
church, circle, clock, cloud, coat, collar, comb, cord, cow, cup,
curtain, cushion,
dog, door, drain, drawer, dress, drop,
ear, egg, engine, eye,
face, farm, feather, finger, fish, flag, floor, fly, foot, fork, fowl, frame,
garden, girl, glove, goat, gun,
hair, hammer, hand, hat, head, heart, hook, horn, horse, hospital, house,
island, jewel,
kettle, key, knee, knife, knot,
leaf, leg, library, line, lip, lock,
map, match, monkey, moon, mouth, muscle,
nail, neck, needle, nerve, net, nose, nut,
office, orange, oven,
parcel, pen, pencil, picture, pig, pin, pipe, plane, plate, plough/plow,
pocket, pot, potato, prison, pump,
rail, rat, receipt, ring, rod, roof, root,
sail, school, scissors, screw, seed, sheep, shelf, ship, shirt, shoe,
skin, skirt, snake, sock, spade, sponge, spoon, spring, square, stamp,
star, station, stem, stick, stocking, stomach, store, street, sun,
table, tail, thread, throat, thumb, ticket, toe, tongue, tooth, town,
train, tray, tree, trousers,
umbrella,
wall, watch, wheel, whip, whistle, window, wing, wire, worm`,
  },
  {
    id: 'qualities',
    label: '性质',
    tone: '#44713b',
    words: `able, acid, angry, automatic, beautiful, black, boiling, bright, broken, brown,
cheap, chemical, chief, clean, clear, common, complex, conscious, cut,
deep, dependent,
early, elastic, electric, equal,
fat, fertile, first, fixed, flat, free, frequent, full,
general, good, great, grey/gray,
hanging, happy, hard, healthy, high, hollow,
important, kind,
like, living, long,
male, married, material, medical, military,
natural, necessary, new, normal,
open,
parallel, past, physical, political, poor, possible, present, private,
probable,
quick, quiet,
ready, red, regular, responsible, right, round,
same, second, separate, serious, sharp, smooth, sticky, stiff, straight,
strong, sudden, sweet,
tall, thick, tight, tired, true,
violent,
waiting, warm, wet, wide, wise,
yellow, young`,
  },
  {
    id: 'opposites',
    label: '反义性质',
    tone: '#8f4d63',
    words: `awake, bad, bent, bitter, blue, certain, cold, complete, cruel,
dark, dead, dear, delicate, different, dirty, dry,
false, feeble, female, foolish, future,
green, ill,
last, late, left, loose, loud, low,
mixed, narrow, old, opposite,
public, rough,
sad, safe, secret, short, shut, simple, slow, small, soft, solid,
special, strange,
thin, white, wrong`,
  },
];

const zh = {
  come: '来', get: '得到', give: '给', go: '去', keep: '保持', let: '让', make: '制作；使', put: '放',
  seem: '似乎', take: '拿；带', be: '是；存在', do: '做', have: '有', say: '说', see: '看见',
  send: '发送', may: '可以；可能', will: '将会', about: '关于', across: '穿过', after: '在之后',
  against: '反对；倚着', among: '在之中', before: '在之前', between: '在两者之间', down: '向下',
  from: '从', over: '在上方', through: '通过', under: '在下面', again: '再一次', enough: '足够',
  tomorrow: '明天', yesterday: '昨天', north: '北', south: '南', east: '东', west: '西', please: '请',
  yes: '是的', account: '账户；叙述', act: '行为；行动', air: '空气', animal: '动物', answer: '回答',
  art: '艺术', attack: '攻击', attention: '注意', authority: '权威', back: '背部；后面',
  balance: '平衡', base: '基础', belief: '信念', birth: '出生', blood: '血液', body: '身体',
  bread: '面包', brother: '兄弟', building: '建筑', business: '生意', care: '照顾', cause: '原因',
  change: '变化', color: '颜色', comfort: '舒适', company: '公司；陪伴', control: '控制',
  country: '国家；乡村', damage: '损害', danger: '危险', daughter: '女儿', day: '一天',
  death: '死亡', decision: '决定', design: '设计', detail: '细节', direction: '方向',
  distance: '距离', drink: '饮料；喝', earth: '地球；土地', education: '教育', effect: '影响',
  end: '结束', event: '事件', example: '例子', experience: '经验', family: '家庭', father: '父亲',
  fear: '害怕', feeling: '感觉', field: '田地；领域', fire: '火', flower: '花', food: '食物',
  friend: '朋友', fruit: '水果', glass: '玻璃；杯子', government: '政府', grass: '草',
  group: '群组', help: '帮助', history: '历史', hope: '希望', hour: '小时', idea: '想法',
  industry: '工业', interest: '兴趣；利息', journey: '旅程', knowledge: '知识', language: '语言',
  law: '法律', learning: '学习', letter: '字母；信', light: '光；轻的', list: '清单',
  love: '爱', machine: '机器', man: '男人', market: '市场', meal: '一餐', memory: '记忆',
  milk: '牛奶', money: '钱', month: '月份', mother: '母亲', mountain: '山', music: '音乐',
  name: '名字', nation: '国家', need: '需要', news: '新闻', night: '夜晚', noise: '噪音',
  number: '数字', offer: '提供', order: '顺序；命令', page: '页面', pain: '疼痛', paper: '纸',
  peace: '和平', person: '人', place: '地方', plant: '植物；种植', play: '玩；戏剧',
  point: '点；观点', power: '力量', price: '价格', process: '过程', question: '问题',
  rain: '雨', reason: '原因', record: '记录', respect: '尊重', river: '河流', road: '道路',
  room: '房间', rule: '规则', salt: '盐', school: '学校', science: '科学', sea: '海',
  sense: '感觉；意义', sister: '姐妹', size: '大小', sky: '天空', sleep: '睡眠', smile: '微笑',
  snow: '雪', society: '社会', son: '儿子', song: '歌曲', sound: '声音', space: '空间',
  start: '开始', story: '故事', summer: '夏天', system: '系统', talk: '谈话', taste: '味道',
  test: '测试', thing: '东西', thought: '想法', time: '时间', trade: '贸易', trouble: '麻烦',
  use: '使用', value: '价值', view: '视野；看法', voice: '声音', walk: '走路', war: '战争',
  water: '水', weather: '天气', week: '星期', wind: '风', winter: '冬天', woman: '女人',
  wood: '木头', word: '单词', work: '工作', writing: '写作', year: '年',
  angle: '角', apple: '苹果', arm: '手臂', baby: '婴儿', bag: '包', ball: '球', bed: '床',
  bird: '鸟', book: '书', bottle: '瓶子', boy: '男孩', brain: '大脑', bridge: '桥',
  camera: '相机', card: '卡片', cat: '猫', chain: '链条', clock: '钟', cloud: '云',
  coat: '外套', cow: '奶牛', cup: '杯子', dog: '狗', door: '门', ear: '耳朵', egg: '蛋',
  eye: '眼睛', face: '脸', farm: '农场', finger: '手指', fish: '鱼', floor: '地板',
  foot: '脚', garden: '花园', girl: '女孩', hair: '头发', hand: '手', hat: '帽子',
  head: '头', heart: '心', horse: '马', house: '房子', island: '岛', key: '钥匙',
  knee: '膝盖', knife: '刀', leaf: '叶子', leg: '腿', library: '图书馆', line: '线',
  map: '地图', moon: '月亮', mouth: '嘴', neck: '脖子', nose: '鼻子', office: '办公室',
  orange: '橙子；橙色', pen: '钢笔', pencil: '铅笔', picture: '图片', plate: '盘子',
  pocket: '口袋', potato: '土豆', prison: '监狱', ring: '戒指', roof: '屋顶',
  seed: '种子', sheep: '羊', shirt: '衬衫', shoe: '鞋', skin: '皮肤', snake: '蛇',
  spoon: '勺子', spring: '春天；弹簧', star: '星星', street: '街道', sun: '太阳',
  table: '桌子', tooth: '牙齿', town: '城镇', train: '火车', tree: '树', umbrella: '伞',
  wall: '墙', watch: '手表；看', wheel: '轮子', window: '窗户', wing: '翅膀',
  able: '能够的', acid: '酸的', angry: '生气的', automatic: '自动的', beautiful: '美丽的',
  black: '黑色的', bright: '明亮的', broken: '破损的', brown: '棕色的', cheap: '便宜的',
  clean: '干净的', clear: '清楚的', common: '常见的', deep: '深的', early: '早的',
  equal: '相等的', fat: '胖的；脂肪', first: '第一的', flat: '平的', free: '自由的；免费的',
  full: '满的', good: '好的', great: '伟大的', happy: '快乐的', hard: '困难的；硬的',
  healthy: '健康的', high: '高的', important: '重要的', kind: '友善的；种类',
  living: '活着的', long: '长的', natural: '自然的', necessary: '必要的', new: '新的',
  open: '打开的', poor: '贫穷的；差的', possible: '可能的', present: '现在的；礼物',
  quick: '快的', quiet: '安静的', ready: '准备好的', red: '红色的', right: '正确的；右边',
  round: '圆的', serious: '严肃的', sharp: '锋利的', smooth: '光滑的', strong: '强壮的',
  sweet: '甜的', tall: '高的', tired: '疲惫的', true: '真实的', warm: '温暖的',
  wet: '湿的', wide: '宽的', wise: '明智的', yellow: '黄色的', young: '年轻的',
  awake: '醒着的', bad: '坏的', bitter: '苦的', blue: '蓝色的', cold: '冷的',
  dark: '黑暗的', dead: '死的', different: '不同的', dirty: '脏的', dry: '干的',
  false: '错误的', female: '女性的', foolish: '愚蠢的', future: '未来的', green: '绿色的',
  late: '迟的', left: '左边', loud: '大声的', low: '低的', narrow: '窄的',
  old: '老的；旧的', public: '公共的', rough: '粗糙的', sad: '悲伤的', safe: '安全的',
  secret: '秘密的', short: '短的', shut: '关闭的', simple: '简单的', slow: '慢的',
  small: '小的', soft: '软的', thin: '薄的；瘦的', white: '白色的', wrong: '错误的',
};

const zhFixes = {
  at: '在；于', by: '靠近；通过；由', in: '在里面', off: '离开；关掉', on: '在上面；开启',
  to: '到；向', up: '向上', with: '和；用', as: '作为；像', for: '为了；给',
  of: '属于；……的', till: '直到', than: '比', a: '一个', the: '这个；那个',
  all: '全部', any: '任何', every: '每一个', little: '小的；少量', much: '许多',
  no: '没有；不', other: '其他的', some: '一些', such: '这样的', that: '那个',
  this: '这个', I: '我', he: '他', you: '你；你们', who: '谁',
  and: '和；并且', because: '因为', but: '但是', or: '或者', if: '如果',
  though: '虽然', while: '当……时；然而', how: '怎样', when: '什么时候；当……时',
  where: '哪里', why: '为什么', ever: '曾经；任何时候', far: '远的；远地',
  forward: '向前', here: '这里', near: '近的；在附近', now: '现在', out: '出去；在外',
  still: '仍然；静止的', then: '然后；那时', there: '那里', together: '一起', well: '好地；健康的',
  almost: '几乎', even: '甚至；平坦的', not: '不', only: '只；仅仅', quite: '相当；完全',
  so: '所以；如此', very: '非常',

  addition: '增加；加法', adjustment: '调整', advertisement: '广告', agreement: '协议；同意',
  amount: '数量；总额', amusement: '娱乐；消遣', apparatus: '器具；设备', approval: '批准；认可',
  argument: '争论；论点', attempt: '尝试', attraction: '吸引力；景点', behavior: '行为',
  bit: '一点；小块', bite: '咬；一口', blow: '打击；吹', brass: '黄铜', breath: '呼吸；气息',
  burn: '烧伤；燃烧', burst: '爆裂；突然爆发', butter: '黄油', canvas: '帆布；画布',
  chalk: '粉笔', chance: '机会；可能性', cloth: '布', coal: '煤', committee: '委员会',
  comparison: '比较', competition: '竞争；比赛', condition: '条件；状况', connection: '连接；关系',
  cook: '厨师；烹调', copper: '铜', copy: '副本；复制', cork: '软木塞；软木',
  cotton: '棉花；棉布', cough: '咳嗽', cover: '盖子；覆盖', crack: '裂缝；破裂',
  credit: '信用；赞扬', crime: '犯罪', crush: '压碎；挤压', cry: '哭声；哭',
  current: '水流；电流；当前的', curve: '曲线；弯曲', debt: '债务', degree: '程度；度数',
  desire: '渴望；愿望', destruction: '破坏', development: '发展', digestion: '消化',
  discovery: '发现', discussion: '讨论', disease: '疾病', disgust: '厌恶',
  distribution: '分配；分布', division: '划分；部门', doubt: '怀疑', driving: '驾驶',
  dust: '灰尘', edge: '边缘', error: '错误', exchange: '交换', existence: '存在',
  expansion: '扩展；膨胀', expert: '专家', fact: '事实', fall: '落下；秋天',
  fiction: '小说；虚构', fight: '打斗；斗争', flame: '火焰', flight: '飞行；航班',
  fold: '折痕；折叠', force: '力量；迫使', form: '形式；表格', front: '前面',
  gold: '金；黄金', grain: '谷物；颗粒', grip: '紧握；控制力', growth: '生长；增长',
  guide: '向导；指南', harbor: '港口；庇护', harmony: '和谐', hate: '仇恨；讨厌',
  hearing: '听力；听证会', heat: '热；加热', hole: '洞', humor: '幽默',
  ice: '冰', impulse: '冲动；推动力', increase: '增加', ink: '墨水',
  insect: '昆虫', instrument: '工具；乐器', insurance: '保险', invention: '发明',
  iron: '铁；熨斗', jelly: '果冻', join: '连接；加入', judge: '法官；判断',
  jump: '跳跃', kick: '踢', kiss: '亲吻', land: '土地；着陆', laugh: '笑；笑声',
  lead: '带领；铅', leather: '皮革', level: '水平；层级', lift: '举起；电梯',
  limit: '限制；限度', linen: '亚麻布', liquid: '液体', look: '看；样子',
  loss: '损失；失去', manager: '经理', mark: '标记；分数', mass: '大量；质量',
  measure: '测量；措施', meat: '肉', meeting: '会议；会面', metal: '金属',
  middle: '中间', mind: '头脑；介意', mine: '矿；我的', minute: '分钟；微小的',
  mist: '薄雾', morning: '早晨', motion: '运动；动作', move: '移动；搬家',
  note: '笔记；便条；音符', observation: '观察', oil: '油', operation: '操作；手术',
  opinion: '意见；看法', organization: '组织', ornament: '装饰品', owner: '所有者',
  paint: '油漆；绘画', part: '部分；零件', paste: '糊状物；粘贴', payment: '付款',
  pleasure: '愉快；乐趣', poison: '毒药', polish: '擦亮；波兰语', porter: '搬运工；门房',
  position: '位置；职位', powder: '粉末', print: '印刷；印记', produce: '生产；农产品',
  profit: '利润', property: '财产；属性', prose: '散文', protest: '抗议',
  pull: '拉', punishment: '惩罚', purpose: '目的', push: '推', quality: '质量；品质',
  range: '范围；山脉', rate: '比率；速度', ray: '光线', reaction: '反应',
  reading: '阅读；读数', regret: '后悔；遗憾', relation: '关系', religion: '宗教',
  representative: '代表', request: '请求', rest: '休息；剩余部分', reward: '奖励',
  rhythm: '节奏', rice: '米；米饭', roll: '卷；滚动', rub: '摩擦',
  run: '跑；运转', sand: '沙子', scale: '规模；刻度；鳞片', seat: '座位',
  secretary: '秘书', selection: '选择；选集', self: '自己；自我', servant: '仆人；服务员',
  sex: '性别；性', shade: '阴影；遮蔽', shake: '摇动', shame: '羞耻',
  shock: '震惊；冲击', side: '一边；侧面', sign: '标志；签名', silk: '丝绸',
  silver: '银；银色', slip: '滑倒；小纸条', slope: '斜坡', smash: '打碎；猛撞',
  smell: '气味；闻', smoke: '烟；吸烟', sneeze: '打喷嚏', soap: '肥皂',
  sort: '种类；分类', soup: '汤', stage: '阶段；舞台', statement: '陈述；声明',
  steam: '蒸汽', steel: '钢', step: '步；步骤', stitch: '针脚；缝',
  stone: '石头', stop: '停止；站点', stretch: '伸展；一段', structure: '结构',
  substance: '物质', sugar: '糖', suggestion: '建议', support: '支持；支撑',
  surprise: '惊喜；使惊讶', swim: '游泳', tax: '税', teaching: '教学；教导',
  tendency: '倾向', theory: '理论', thunder: '雷声', tin: '锡；罐头',
  top: '顶部', touch: '触摸；接触', transport: '运输', trick: '把戏；诀窍',
  turn: '转动；轮到', twist: '扭转；弯曲', unit: '单位；单元', verse: '诗句',
  vessel: '船；容器；血管', wash: '洗；洗涤', waste: '浪费；废物', wave: '波浪；挥手',
  wax: '蜡', way: '路；方法', weight: '重量', wine: '葡萄酒', wool: '羊毛',
  wound: '伤口；伤害',

  ant: '蚂蚁', arch: '拱门；拱形', army: '军队', band: '带子；乐队', basin: '盆；水池',
  basket: '篮子', bath: '洗澡；浴缸', bee: '蜜蜂', bell: '铃；钟', berry: '浆果',
  blade: '刀刃；叶片', board: '木板；委员会', boat: '船', bone: '骨头',
  boot: '靴子', box: '盒子；箱子', brake: '刹车', branch: '树枝；分支',
  brick: '砖', brush: '刷子；刷', bucket: '桶', bulb: '灯泡；球茎',
  button: '按钮；纽扣', cake: '蛋糕', cart: '手推车；马车', carriage: '车厢；马车',
  cheese: '奶酪', chest: '胸部；箱子', chin: '下巴', church: '教堂',
  circle: '圆；圈', collar: '衣领；项圈', comb: '梳子', cord: '绳子；电线',
  curtain: '窗帘', cushion: '垫子', drain: '排水管；排水', drawer: '抽屉',
  dress: '连衣裙；穿衣', drop: '滴；落下', engine: '发动机', feather: '羽毛',
  flag: '旗帜', fly: '苍蝇；飞', fork: '叉子；分叉', fowl: '家禽',
  frame: '框架', glove: '手套', goat: '山羊', gun: '枪', hammer: '锤子',
  hook: '钩子', horn: '角；喇叭', hospital: '医院', jewel: '宝石',
  kettle: '水壶', knot: '结', lip: '嘴唇', lock: '锁；锁上', match: '火柴；比赛',
  monkey: '猴子', muscle: '肌肉', nail: '钉子；指甲', needle: '针',
  nerve: '神经；勇气', net: '网', nut: '坚果；螺母', oven: '烤箱',
  parcel: '包裹', pig: '猪', pin: '别针；大头针', pipe: '管子；烟斗',
  plane: '飞机；平面', plough: '犁', pot: '锅；罐', pump: '泵；打气筒',
  rail: '栏杆；铁轨', rat: '老鼠', receipt: '收据', rod: '杆；棍',
  root: '根', sail: '帆；航行', scissors: '剪刀', screw: '螺丝；拧',
  shelf: '架子', ship: '船；舰', skirt: '裙子', sock: '短袜', spade: '铲子',
  sponge: '海绵', square: '正方形；广场', stamp: '邮票；印章', station: '车站；站',
  stem: '茎；词干', stick: '棍子；粘住', stocking: '长袜', stomach: '胃；肚子',
  store: '商店；储存', tail: '尾巴', thread: '线；线索', throat: '喉咙',
  thumb: '拇指', ticket: '票', toe: '脚趾', tongue: '舌头；语言',
  tray: '托盘', trousers: '裤子', whip: '鞭子；抽打', whistle: '口哨；哨声',
  wire: '金属丝；电线', worm: '虫；蠕虫',

  boiling: '沸腾的；极热的', chemical: '化学的；化学品', chief: '主要的；首领',
  complex: '复杂的', conscious: '有意识的；清醒的', cut: '切开的；割伤的',
  dependent: '依赖的', elastic: '有弹性的', electric: '电的', fertile: '肥沃的；多产的',
  fixed: '固定的', frequent: '频繁的', general: '一般的；将军', grey: '灰色的',
  hanging: '悬挂的', hollow: '空心的；凹陷的', like: '相似的；喜欢',
  male: '男性的；雄性的', married: '已婚的', material: '物质的；材料',
  medical: '医学的', military: '军事的', normal: '正常的', parallel: '平行的',
  past: '过去的；过去', physical: '身体的；物理的', political: '政治的',
  private: '私人的', probable: '很可能的', regular: '规则的；定期的',
  responsible: '负责的', same: '相同的', second: '第二的；秒', separate: '分开的',
  sticky: '黏的', stiff: '僵硬的', straight: '直的；直接的', sudden: '突然的',
  thick: '厚的；浓的', tight: '紧的', violent: '暴力的；猛烈的', waiting: '等待的',
  bent: '弯曲的', certain: '确定的；某个', complete: '完整的；完成',
  cruel: '残忍的', dear: '亲爱的；昂贵的', delicate: '精细的；脆弱的',
  feeble: '虚弱的', ill: '生病的', last: '最后的；持续', loose: '松的',
  mixed: '混合的', opposite: '相反的；对面的', solid: '固体的；结实的',
  special: '特别的', strange: '奇怪的；陌生的',
};

const translations = { ...zh, ...zhFixes };

const ipa = {
  "come": "/kʌm/",
  "get": "/ɡet/",
  "give": "/ɡɪv/",
  "go": "/ɡoʊ/",
  "keep": "/kiːp/",
  "let": "/let/",
  "make": "/meɪk/",
  "put": "/pʊt/",
  "seem": "/siːm/",
  "take": "/teɪk/",
  "be": "/biː/",
  "do": "/duː/",
  "have": "/hæv/",
  "say": "/seɪ/",
  "see": "/siː/",
  "send": "/send/",
  "may": "/meɪ/",
  "will": "/wɪl/",
  "about": "/əbaʊt/",
  "across": "/əkrɔs/",
  "after": "/æftɚ/",
  "against": "/əɡenst/",
  "among": "/əmʌŋ/",
  "at": "/æt/",
  "before": "/bɪfɔr/",
  "between": "/bɪtwiːn/",
  "by": "/baɪ/",
  "down": "/daʊn/",
  "from": "/frʌm/",
  "in": "/ɪn/",
  "off": "/ɔf/",
  "on": "/ɑn/",
  "over": "/oʊvɚ/",
  "through": "/θruː/",
  "to": "/tuː/",
  "under": "/ʌndɚ/",
  "up": "/ʌp/",
  "with": "/wɪð/",
  "as": "/æz/",
  "for": "/fɔr/",
  "of": "/ʌv/",
  "till": "/tɪl/",
  "than": "/ðæn/",
  "a": "/ə/",
  "the": "/ðə/",
  "all": "/ɔl/",
  "any": "/eniː/",
  "every": "/evɚiː/",
  "little": "/lɪtəl/",
  "much": "/mʌtʃ/",
  "no": "/noʊ/",
  "other": "/ʌðɚ/",
  "some": "/sʌm/",
  "such": "/sʌtʃ/",
  "that": "/ðæt/",
  "this": "/ðɪs/",
  "I": "/aɪ/",
  "he": "/hiː/",
  "you": "/juː/",
  "who": "/huː/",
  "and": "/ənd/",
  "because": "/bɪkɔz/",
  "but": "/bʌt/",
  "or": "/ɔr/",
  "if": "/ɪf/",
  "though": "/ðoʊ/",
  "while": "/waɪl/",
  "how": "/haʊ/",
  "when": "/wen/",
  "where": "/wer/",
  "why": "/waɪ/",
  "again": "/əɡen/",
  "ever": "/evɚ/",
  "far": "/fɑr/",
  "forward": "/fɔrwɚd/",
  "here": "/hiːr/",
  "near": "/nɪr/",
  "now": "/naʊ/",
  "out": "/aʊt/",
  "still": "/stɪl/",
  "then": "/ðen/",
  "there": "/ðer/",
  "together": "/təɡeðɚ/",
  "well": "/wel/",
  "almost": "/ɔlmoʊst/",
  "enough": "/ɪnʌf/",
  "even": "/iːvɪn/",
  "not": "/nɑt/",
  "only": "/oʊnliː/",
  "quite": "/kwaɪt/",
  "so": "/soʊ/",
  "very": "/veriː/",
  "tomorrow": "/təmɑroʊ/",
  "yesterday": "/jestɚdeɪ/",
  "north": "/nɔrθ/",
  "south": "/saʊθ/",
  "east": "/iːst/",
  "west": "/west/",
  "please": "/pliːz/",
  "yes": "/jes/",
  "account": "/əkaʊnt/",
  "act": "/ækt/",
  "addition": "/ədɪʃən/",
  "adjustment": "/ədʒʌstmənt/",
  "advertisement": "/ædvɝtəzmənt/",
  "agreement": "/əɡriːmənt/",
  "air": "/er/",
  "amount": "/əmaʊnt/",
  "amusement": "/əmjuːzmənt/",
  "animal": "/ænəməl/",
  "answer": "/ænsɚ/",
  "apparatus": "/æpɚætəs/",
  "approval": "/əpruːvəl/",
  "argument": "/ɑrɡjəmənt/",
  "art": "/ɑrt/",
  "attack": "/ətæk/",
  "attempt": "/ətempt/",
  "attention": "/ətenʃən/",
  "attraction": "/ətrækʃən/",
  "authority": "/əθɔrətiː/",
  "back": "/bæk/",
  "balance": "/bæləns/",
  "base": "/beɪs/",
  "behavior": "/bɪheɪvjɚ/",
  "belief": "/bɪliːf/",
  "birth": "/bɝθ/",
  "bit": "/bɪt/",
  "bite": "/baɪt/",
  "blood": "/blʌd/",
  "blow": "/bloʊ/",
  "body": "/bɑdiː/",
  "brass": "/bræs/",
  "bread": "/bred/",
  "breath": "/breθ/",
  "brother": "/brʌðɚ/",
  "building": "/bɪldɪŋ/",
  "burn": "/bɝn/",
  "burst": "/bɝst/",
  "business": "/bɪznəs/",
  "butter": "/bʌtɚ/",
  "canvas": "/kænvəs/",
  "care": "/ker/",
  "cause": "/kɑz/",
  "chalk": "/tʃɑk/",
  "chance": "/tʃæns/",
  "change": "/tʃeɪndʒ/",
  "cloth": "/klɔθ/",
  "coal": "/koʊl/",
  "color": "/kʌlɚ/",
  "comfort": "/kʌmfɚt/",
  "committee": "/kəmɪtiː/",
  "company": "/kʌmpəniː/",
  "comparison": "/kəmperəsən/",
  "competition": "/kɑmpətɪʃən/",
  "condition": "/kəndɪʃən/",
  "connection": "/kənekʃən/",
  "control": "/kəntroʊl/",
  "cook": "/kʊk/",
  "copper": "/kɑpɚ/",
  "copy": "/kɑpiː/",
  "cork": "/kɔrk/",
  "cotton": "/kɑtən/",
  "cough": "/kɑf/",
  "country": "/kʌntriː/",
  "cover": "/kʌvɚ/",
  "crack": "/kræk/",
  "credit": "/kredət/",
  "crime": "/kraɪm/",
  "crush": "/krʌʃ/",
  "cry": "/kraɪ/",
  "current": "/kɝənt/",
  "curve": "/kɝv/",
  "damage": "/dæmədʒ/",
  "danger": "/deɪndʒɚ/",
  "daughter": "/dɔtɚ/",
  "day": "/deɪ/",
  "death": "/deθ/",
  "debt": "/det/",
  "decision": "/dɪsɪʒən/",
  "degree": "/dɪɡriː/",
  "design": "/dɪzaɪn/",
  "desire": "/dɪzaɪɚ/",
  "destruction": "/dɪstrʌkʃən/",
  "detail": "/dɪteɪl/",
  "development": "/dɪveləpmənt/",
  "digestion": "/daɪdʒestʃən/",
  "direction": "/dɚekʃən/",
  "discovery": "/dɪskʌvɚiː/",
  "discussion": "/dɪskʌʃən/",
  "disease": "/dɪziːz/",
  "disgust": "/dɪsɡʌst/",
  "distance": "/dɪstəns/",
  "distribution": "/dɪstrəbjuːʃən/",
  "division": "/dɪvɪʒən/",
  "doubt": "/daʊt/",
  "drink": "/drɪŋk/",
  "driving": "/draɪvɪŋ/",
  "dust": "/dʌst/",
  "earth": "/ɝθ/",
  "edge": "/edʒ/",
  "education": "/edʒəkeɪʃən/",
  "effect": "/ɪfekt/",
  "end": "/end/",
  "error": "/erɚ/",
  "event": "/ɪvent/",
  "example": "/ɪɡzæmpəl/",
  "exchange": "/ɪkstʃeɪndʒ/",
  "existence": "/eɡzɪstəns/",
  "expansion": "/ɪkspænʃən/",
  "experience": "/ɪkspɪriːəns/",
  "expert": "/ekspɚt/",
  "fact": "/fækt/",
  "fall": "/fɔl/",
  "family": "/fæməliː/",
  "father": "/fɑðɚ/",
  "fear": "/fɪr/",
  "feeling": "/fiːlɪŋ/",
  "fiction": "/fɪkʃən/",
  "field": "/fiːld/",
  "fight": "/faɪt/",
  "fire": "/faɪɚ/",
  "flame": "/fleɪm/",
  "flight": "/flaɪt/",
  "flower": "/flaʊɚ/",
  "fold": "/foʊld/",
  "food": "/fuːd/",
  "force": "/fɔrs/",
  "form": "/fɔrm/",
  "friend": "/frend/",
  "front": "/frʌnt/",
  "fruit": "/fruːt/",
  "glass": "/ɡlæs/",
  "gold": "/ɡoʊld/",
  "government": "/ɡʌvɚmənt/",
  "grain": "/ɡreɪn/",
  "grass": "/ɡræs/",
  "grip": "/ɡrɪp/",
  "group": "/ɡruːp/",
  "growth": "/ɡroʊθ/",
  "guide": "/ɡaɪd/",
  "harbor": "/hɑrbɚ/",
  "harmony": "/hɑrməniː/",
  "hate": "/heɪt/",
  "hearing": "/hiːrɪŋ/",
  "heat": "/hiːt/",
  "help": "/help/",
  "history": "/hɪstɚiː/",
  "hole": "/hoʊl/",
  "hope": "/hoʊp/",
  "hour": "/aʊɚ/",
  "humor": "/hjuːmɚ/",
  "ice": "/aɪs/",
  "idea": "/aɪdiːə/",
  "impulse": "/ɪmpəls/",
  "increase": "/ɪnkriːs/",
  "industry": "/ɪndəstriː/",
  "ink": "/ɪŋk/",
  "insect": "/ɪnsekt/",
  "instrument": "/ɪnstrəmənt/",
  "insurance": "/ɪnʃʊrəns/",
  "interest": "/ɪntrəst/",
  "invention": "/ɪnvenʃən/",
  "iron": "/aɪɚn/",
  "jelly": "/dʒeliː/",
  "join": "/dʒɔɪn/",
  "journey": "/dʒɝniː/",
  "judge": "/dʒʌdʒ/",
  "jump": "/dʒʌmp/",
  "kick": "/kɪk/",
  "kiss": "/kɪs/",
  "knowledge": "/nɑlədʒ/",
  "land": "/lænd/",
  "language": "/læŋɡwədʒ/",
  "laugh": "/læf/",
  "law": "/lɔ/",
  "lead": "/led/",
  "learning": "/lɝnɪŋ/",
  "leather": "/leðɚ/",
  "letter": "/letɚ/",
  "level": "/levəl/",
  "lift": "/lɪft/",
  "light": "/laɪt/",
  "limit": "/lɪmət/",
  "linen": "/lɪnən/",
  "liquid": "/lɪkwəd/",
  "list": "/lɪst/",
  "look": "/lʊk/",
  "loss": "/lɔs/",
  "love": "/lʌv/",
  "machine": "/məʃiːn/",
  "man": "/mæn/",
  "manager": "/mænədʒɚ/",
  "mark": "/mɑrk/",
  "market": "/mɑrkət/",
  "mass": "/mæs/",
  "meal": "/miːl/",
  "measure": "/meʒɚ/",
  "meat": "/miːt/",
  "meeting": "/miːtɪŋ/",
  "memory": "/memɚiː/",
  "metal": "/metəl/",
  "middle": "/mɪdəl/",
  "milk": "/mɪlk/",
  "mind": "/maɪnd/",
  "mine": "/maɪn/",
  "minute": "/mɪnət/",
  "mist": "/mɪst/",
  "money": "/mʌniː/",
  "month": "/mʌnθ/",
  "morning": "/mɔrnɪŋ/",
  "mother": "/mʌðɚ/",
  "motion": "/moʊʃən/",
  "mountain": "/maʊntən/",
  "move": "/muːv/",
  "music": "/mjuːzɪk/",
  "name": "/neɪm/",
  "nation": "/neɪʃən/",
  "need": "/niːd/",
  "news": "/nuːz/",
  "night": "/naɪt/",
  "noise": "/nɔɪz/",
  "note": "/noʊt/",
  "number": "/nʌmbɚ/",
  "observation": "/ɑbzɚveɪʃən/",
  "offer": "/ɔfɚ/",
  "oil": "/ɔɪl/",
  "operation": "/ɑpɚeɪʃən/",
  "opinion": "/əpɪnjən/",
  "order": "/ɔrdɚ/",
  "organization": "/ɔrɡənəzeɪʃən/",
  "ornament": "/ɔrnəmənt/",
  "owner": "/oʊnɚ/",
  "page": "/peɪdʒ/",
  "pain": "/peɪn/",
  "paint": "/peɪnt/",
  "paper": "/peɪpɚ/",
  "part": "/pɑrt/",
  "paste": "/peɪst/",
  "payment": "/peɪmənt/",
  "peace": "/piːs/",
  "person": "/pɝsən/",
  "place": "/pleɪs/",
  "plant": "/plænt/",
  "play": "/pleɪ/",
  "pleasure": "/pleʒɚ/",
  "point": "/pɔɪnt/",
  "poison": "/pɔɪzən/",
  "polish": "/pɑlɪʃ/",
  "porter": "/pɔrtɚ/",
  "position": "/pəzɪʃən/",
  "powder": "/paʊdɚ/",
  "power": "/paʊɚ/",
  "price": "/praɪs/",
  "print": "/prɪnt/",
  "process": "/prɑses/",
  "produce": "/prəduːs/",
  "profit": "/prɑfət/",
  "property": "/prɑpɚtiː/",
  "prose": "/proʊz/",
  "protest": "/proʊtest/",
  "pull": "/pʊl/",
  "punishment": "/pʌnɪʃmənt/",
  "purpose": "/pɝpəs/",
  "push": "/pʊʃ/",
  "quality": "/kwɑlətiː/",
  "question": "/kwestʃən/",
  "rain": "/reɪn/",
  "range": "/reɪndʒ/",
  "rate": "/reɪt/",
  "ray": "/reɪ/",
  "reaction": "/riːækʃən/",
  "reading": "/riːdɪŋ/",
  "reason": "/riːzən/",
  "record": "/rəkɔrd/",
  "regret": "/rəɡret/",
  "relation": "/riːleɪʃən/",
  "religion": "/rɪlɪdʒən/",
  "representative": "/reprəzentətɪv/",
  "request": "/rɪkwest/",
  "respect": "/rɪspekt/",
  "rest": "/rest/",
  "reward": "/rɪwɔrd/",
  "rhythm": "/rɪðəm/",
  "rice": "/raɪs/",
  "river": "/rɪvɚ/",
  "road": "/roʊd/",
  "roll": "/roʊl/",
  "room": "/ruːm/",
  "rub": "/rʌb/",
  "rule": "/ruːl/",
  "run": "/rʌn/",
  "salt": "/sɔlt/",
  "sand": "/sænd/",
  "scale": "/skeɪl/",
  "science": "/saɪəns/",
  "sea": "/siː/",
  "seat": "/siːt/",
  "secretary": "/sekrəteriː/",
  "selection": "/səlekʃən/",
  "self": "/self/",
  "sense": "/sens/",
  "servant": "/sɝvənt/",
  "sex": "/seks/",
  "shade": "/ʃeɪd/",
  "shake": "/ʃeɪk/",
  "shame": "/ʃeɪm/",
  "shock": "/ʃɑk/",
  "side": "/saɪd/",
  "sign": "/saɪn/",
  "silk": "/sɪlk/",
  "silver": "/sɪlvɚ/",
  "sister": "/sɪstɚ/",
  "size": "/saɪz/",
  "sky": "/skaɪ/",
  "sleep": "/sliːp/",
  "slip": "/slɪp/",
  "slope": "/sloʊp/",
  "smash": "/smæʃ/",
  "smell": "/smel/",
  "smile": "/smaɪl/",
  "smoke": "/smoʊk/",
  "sneeze": "/sniːz/",
  "snow": "/snoʊ/",
  "soap": "/soʊp/",
  "society": "/səsaɪətiː/",
  "son": "/sʌn/",
  "song": "/sɔŋ/",
  "sort": "/sɔrt/",
  "sound": "/saʊnd/",
  "soup": "/suːp/",
  "space": "/speɪs/",
  "stage": "/steɪdʒ/",
  "start": "/stɑrt/",
  "statement": "/steɪtmənt/",
  "steam": "/stiːm/",
  "steel": "/stiːl/",
  "step": "/step/",
  "stitch": "/stɪtʃ/",
  "stone": "/stoʊn/",
  "stop": "/stɑp/",
  "story": "/stɔriː/",
  "stretch": "/stretʃ/",
  "structure": "/strʌktʃɚ/",
  "substance": "/sʌbstəns/",
  "sugar": "/ʃʊɡɚ/",
  "suggestion": "/sədʒestʃən/",
  "summer": "/sʌmɚ/",
  "support": "/səpɔrt/",
  "surprise": "/sɚpraɪz/",
  "swim": "/swɪm/",
  "system": "/sɪstəm/",
  "talk": "/tɔk/",
  "taste": "/teɪst/",
  "tax": "/tæks/",
  "teaching": "/tiːtʃɪŋ/",
  "tendency": "/tendənsiː/",
  "test": "/test/",
  "theory": "/θɪriː/",
  "thing": "/θɪŋ/",
  "thought": "/θɔt/",
  "thunder": "/θʌndɚ/",
  "time": "/taɪm/",
  "tin": "/tɪn/",
  "top": "/tɑp/",
  "touch": "/tʌtʃ/",
  "trade": "/treɪd/",
  "transport": "/trænspɔrt/",
  "trick": "/trɪk/",
  "trouble": "/trʌbəl/",
  "turn": "/tɝn/",
  "twist": "/twɪst/",
  "unit": "/juːnət/",
  "use": "/juːs/",
  "value": "/væljuː/",
  "verse": "/vɝs/",
  "vessel": "/vesəl/",
  "view": "/vjuː/",
  "voice": "/vɔɪs/",
  "walk": "/wɔk/",
  "war": "/wɔr/",
  "wash": "/wɑʃ/",
  "waste": "/weɪst/",
  "water": "/wɔtɚ/",
  "wave": "/weɪv/",
  "wax": "/wæks/",
  "way": "/weɪ/",
  "weather": "/weðɚ/",
  "week": "/wiːk/",
  "weight": "/weɪt/",
  "wind": "/waɪnd/",
  "wine": "/waɪn/",
  "winter": "/wɪntɚ/",
  "woman": "/wʊmən/",
  "wood": "/wʊd/",
  "wool": "/wʊl/",
  "word": "/wɝd/",
  "work": "/wɝk/",
  "wound": "/waʊnd/",
  "writing": "/raɪtɪŋ/",
  "year": "/jɪr/",
  "angle": "/æŋɡəl/",
  "ant": "/ænt/",
  "apple": "/æpəl/",
  "arch": "/ɑrtʃ/",
  "arm": "/ɑrm/",
  "army": "/ɑrmiː/",
  "baby": "/beɪbiː/",
  "bag": "/bæɡ/",
  "ball": "/bɔl/",
  "band": "/bænd/",
  "basin": "/beɪsən/",
  "basket": "/bæskət/",
  "bath": "/bæθ/",
  "bed": "/bed/",
  "bee": "/biː/",
  "bell": "/bel/",
  "berry": "/beriː/",
  "bird": "/bɝd/",
  "blade": "/bleɪd/",
  "board": "/bɔrd/",
  "boat": "/boʊt/",
  "bone": "/boʊn/",
  "book": "/bʊk/",
  "boot": "/buːt/",
  "bottle": "/bɑtəl/",
  "box": "/bɑks/",
  "boy": "/bɔɪ/",
  "brain": "/breɪn/",
  "brake": "/breɪk/",
  "branch": "/bræntʃ/",
  "brick": "/brɪk/",
  "bridge": "/brɪdʒ/",
  "brush": "/brʌʃ/",
  "bucket": "/bʌkət/",
  "bulb": "/bʌlb/",
  "button": "/bʌtən/",
  "cake": "/keɪk/",
  "camera": "/kæmɚə/",
  "card": "/kɑrd/",
  "cart": "/kɑrt/",
  "carriage": "/kærɪdʒ/",
  "cat": "/kæt/",
  "chain": "/tʃeɪn/",
  "cheese": "/tʃiːz/",
  "chest": "/tʃest/",
  "chin": "/tʃɪn/",
  "church": "/tʃɝtʃ/",
  "circle": "/sɝkəl/",
  "clock": "/klɑk/",
  "cloud": "/klaʊd/",
  "coat": "/koʊt/",
  "collar": "/kɑlɚ/",
  "comb": "/koʊm/",
  "cord": "/kɔrd/",
  "cow": "/kaʊ/",
  "cup": "/kʌp/",
  "curtain": "/kɝtən/",
  "cushion": "/kʊʃən/",
  "dog": "/dɔɡ/",
  "door": "/dɔr/",
  "drain": "/dreɪn/",
  "drawer": "/drɔr/",
  "dress": "/dres/",
  "drop": "/drɑp/",
  "ear": "/iːr/",
  "egg": "/eɡ/",
  "engine": "/endʒən/",
  "eye": "/aɪ/",
  "face": "/feɪs/",
  "farm": "/fɑrm/",
  "feather": "/feðɚ/",
  "finger": "/fɪŋɡɚ/",
  "fish": "/fɪʃ/",
  "flag": "/flæɡ/",
  "floor": "/flɔr/",
  "fly": "/flaɪ/",
  "foot": "/fʊt/",
  "fork": "/fɔrk/",
  "fowl": "/faʊl/",
  "frame": "/freɪm/",
  "garden": "/ɡɑrdən/",
  "girl": "/ɡɝl/",
  "glove": "/ɡlʌv/",
  "goat": "/ɡoʊt/",
  "gun": "/ɡʌn/",
  "hair": "/her/",
  "hammer": "/hæmɚ/",
  "hand": "/hænd/",
  "hat": "/hæt/",
  "head": "/hed/",
  "heart": "/hɑrt/",
  "hook": "/hʊk/",
  "horn": "/hɔrn/",
  "horse": "/hɔrs/",
  "hospital": "/hɑspɪtəl/",
  "house": "/haʊs/",
  "island": "/aɪlənd/",
  "jewel": "/dʒuːəl/",
  "kettle": "/ketəl/",
  "key": "/kiː/",
  "knee": "/niː/",
  "knife": "/naɪf/",
  "knot": "/nɑt/",
  "leaf": "/liːf/",
  "leg": "/leɡ/",
  "library": "/laɪbreriː/",
  "line": "/laɪn/",
  "lip": "/lɪp/",
  "lock": "/lɑk/",
  "map": "/mæp/",
  "match": "/mætʃ/",
  "monkey": "/mʌŋkiː/",
  "moon": "/muːn/",
  "mouth": "/maʊθ/",
  "muscle": "/mʌsəl/",
  "nail": "/neɪl/",
  "neck": "/nek/",
  "needle": "/niːdəl/",
  "nerve": "/nɝv/",
  "net": "/net/",
  "nose": "/noʊz/",
  "nut": "/nʌt/",
  "office": "/ɔfɪs/",
  "orange": "/ɔrəndʒ/",
  "oven": "/ʌvən/",
  "parcel": "/pɑrsəl/",
  "pen": "/pen/",
  "pencil": "/pensəl/",
  "picture": "/pɪktʃɚ/",
  "pig": "/pɪɡ/",
  "pin": "/pɪn/",
  "pipe": "/paɪp/",
  "plane": "/pleɪn/",
  "plate": "/pleɪt/",
  "plough": "/plaʊ/",
  "pocket": "/pɑkət/",
  "pot": "/pɑt/",
  "potato": "/pəteɪtoʊ/",
  "prison": "/prɪzən/",
  "pump": "/pʌmp/",
  "rail": "/reɪl/",
  "rat": "/ræt/",
  "receipt": "/rɪsiːt/",
  "ring": "/rɪŋ/",
  "rod": "/rɑd/",
  "roof": "/ruːf/",
  "root": "/ruːt/",
  "sail": "/seɪl/",
  "school": "/skuːl/",
  "scissors": "/sɪzɚz/",
  "screw": "/skruː/",
  "seed": "/siːd/",
  "sheep": "/ʃiːp/",
  "shelf": "/ʃelf/",
  "ship": "/ʃɪp/",
  "shirt": "/ʃɝt/",
  "shoe": "/ʃuː/",
  "skin": "/skɪn/",
  "skirt": "/skɝt/",
  "snake": "/sneɪk/",
  "sock": "/sɑk/",
  "spade": "/speɪd/",
  "sponge": "/spʌndʒ/",
  "spoon": "/spuːn/",
  "spring": "/sprɪŋ/",
  "square": "/skwer/",
  "stamp": "/stæmp/",
  "star": "/stɑr/",
  "station": "/steɪʃən/",
  "stem": "/stem/",
  "stick": "/stɪk/",
  "stocking": "/stɑkɪŋ/",
  "stomach": "/stʌmək/",
  "store": "/stɔr/",
  "street": "/striːt/",
  "sun": "/sʌn/",
  "table": "/teɪbəl/",
  "tail": "/teɪl/",
  "thread": "/θred/",
  "throat": "/θroʊt/",
  "thumb": "/θʌm/",
  "ticket": "/tɪkət/",
  "toe": "/toʊ/",
  "tongue": "/tʌŋ/",
  "tooth": "/tuːθ/",
  "town": "/taʊn/",
  "train": "/treɪn/",
  "tray": "/treɪ/",
  "tree": "/triː/",
  "trousers": "/traʊzɚz/",
  "umbrella": "/əmbrelə/",
  "wall": "/wɔl/",
  "watch": "/wɑtʃ/",
  "wheel": "/wiːl/",
  "whip": "/wɪp/",
  "whistle": "/wɪsəl/",
  "window": "/wɪndoʊ/",
  "wing": "/wɪŋ/",
  "wire": "/waɪɚ/",
  "worm": "/wɝm/",
  "able": "/eɪbəl/",
  "acid": "/æsəd/",
  "angry": "/æŋɡriː/",
  "automatic": "/ɔtəmætɪk/",
  "beautiful": "/bjuːtəfəl/",
  "black": "/blæk/",
  "boiling": "/bɔɪlɪŋ/",
  "bright": "/braɪt/",
  "broken": "/broʊkən/",
  "brown": "/braʊn/",
  "cheap": "/tʃiːp/",
  "chemical": "/keməkəl/",
  "chief": "/tʃiːf/",
  "clean": "/kliːn/",
  "clear": "/klɪr/",
  "common": "/kɑmən/",
  "complex": "/kɑmpleks/",
  "conscious": "/kɑnʃəs/",
  "cut": "/kʌt/",
  "deep": "/diːp/",
  "dependent": "/dɪpendənt/",
  "early": "/ɝliː/",
  "elastic": "/ɪlæstɪk/",
  "electric": "/ɪlektrɪk/",
  "equal": "/iːkwəl/",
  "fat": "/fæt/",
  "fertile": "/fɝtəl/",
  "first": "/fɝst/",
  "fixed": "/fɪkst/",
  "flat": "/flæt/",
  "free": "/friː/",
  "frequent": "/friːkwənt/",
  "full": "/fʊl/",
  "general": "/dʒenɚəl/",
  "good": "/ɡʊd/",
  "great": "/ɡreɪt/",
  "grey": "/ɡreɪ/",
  "hanging": "/hæŋɪŋ/",
  "happy": "/hæpiː/",
  "hard": "/hɑrd/",
  "healthy": "/helθiː/",
  "high": "/haɪ/",
  "hollow": "/hɑloʊ/",
  "important": "/ɪmpɔrtənt/",
  "kind": "/kaɪnd/",
  "like": "/laɪk/",
  "living": "/lɪvɪŋ/",
  "long": "/lɔŋ/",
  "male": "/meɪl/",
  "married": "/meriːd/",
  "material": "/mətɪriːəl/",
  "medical": "/medəkəl/",
  "military": "/mɪləteriː/",
  "natural": "/nætʃɚəl/",
  "necessary": "/nesəseriː/",
  "new": "/nuː/",
  "normal": "/nɔrməl/",
  "open": "/oʊpən/",
  "parallel": "/perəlel/",
  "past": "/pæst/",
  "physical": "/fɪzɪkəl/",
  "political": "/pəlɪtəkəl/",
  "poor": "/puːr/",
  "possible": "/pɑsəbəl/",
  "present": "/prezənt/",
  "private": "/praɪvət/",
  "probable": "/prɑbəbəl/",
  "quick": "/kwɪk/",
  "quiet": "/kwaɪət/",
  "ready": "/rediː/",
  "red": "/red/",
  "regular": "/reɡjəlɚ/",
  "responsible": "/riːspɑnsəbəl/",
  "right": "/raɪt/",
  "round": "/raʊnd/",
  "same": "/seɪm/",
  "second": "/sekənd/",
  "separate": "/sepɚeɪt/",
  "serious": "/sɪriːəs/",
  "sharp": "/ʃɑrp/",
  "smooth": "/smuːð/",
  "sticky": "/stɪkiː/",
  "stiff": "/stɪf/",
  "straight": "/streɪt/",
  "strong": "/strɔŋ/",
  "sudden": "/sʌdən/",
  "sweet": "/swiːt/",
  "tall": "/tɔl/",
  "thick": "/θɪk/",
  "tight": "/taɪt/",
  "tired": "/taɪɚd/",
  "true": "/truː/",
  "violent": "/vaɪələnt/",
  "waiting": "/weɪtɪŋ/",
  "warm": "/wɔrm/",
  "wet": "/wet/",
  "wide": "/waɪd/",
  "wise": "/waɪz/",
  "yellow": "/jeloʊ/",
  "young": "/jʌŋ/",
  "awake": "/əweɪk/",
  "bad": "/bæd/",
  "bent": "/bent/",
  "bitter": "/bɪtɚ/",
  "blue": "/bluː/",
  "certain": "/sɝtən/",
  "cold": "/koʊld/",
  "complete": "/kəmpliːt/",
  "cruel": "/kruːəl/",
  "dark": "/dɑrk/",
  "dead": "/ded/",
  "dear": "/dɪr/",
  "delicate": "/deləkət/",
  "different": "/dɪfɚənt/",
  "dirty": "/dɝtiː/",
  "dry": "/draɪ/",
  "false": "/fɔls/",
  "feeble": "/fiːbəl/",
  "female": "/fiːmeɪl/",
  "foolish": "/fuːlɪʃ/",
  "future": "/fjuːtʃɚ/",
  "green": "/ɡriːn/",
  "ill": "/ɪl/",
  "last": "/læst/",
  "late": "/leɪt/",
  "left": "/left/",
  "loose": "/luːs/",
  "loud": "/laʊd/",
  "low": "/loʊ/",
  "mixed": "/mɪkst/",
  "narrow": "/neroʊ/",
  "old": "/oʊld/",
  "opposite": "/ɑpəzət/",
  "public": "/pʌblɪk/",
  "rough": "/rʌf/",
  "sad": "/sæd/",
  "safe": "/seɪf/",
  "secret": "/siːkrət/",
  "short": "/ʃɔrt/",
  "shut": "/ʃʌt/",
  "simple": "/sɪmpəl/",
  "slow": "/sloʊ/",
  "small": "/smɔl/",
  "soft": "/sɑft/",
  "solid": "/sɑləd/",
  "special": "/speʃəl/",
  "strange": "/streɪndʒ/",
  "thin": "/θɪn/",
  "white": "/waɪt/",
  "wrong": "/rɔŋ/",
};

const cleanToken = (word) => word.trim().replace(/\s+/g, ' ').replace(/[.。]/g, '');

export const groups = rawGroups.map((group) => ({
  ...group,
  count: group.words.split(',').map(cleanToken).filter(Boolean).length,
}));

export const words = rawGroups.flatMap((group) =>
  group.words
    .split(',')
    .map(cleanToken)
    .filter(Boolean)
    .map((word, index) => {
      const speakWord = word.includes('/') ? word.split('/')[0].trim() : word;
      return {
        id: `${group.id}-${index}-${speakWord.toLowerCase()}`,
        word,
        speakWord,
        groupId: group.id,
        groupLabel: group.label,
        tone: group.tone,
        zh: translations[speakWord] || '释义待补充',
        ipa: ipa[speakWord] || '',
      };
    }),
);
