const rawGroups = [
  {
    id: 'operations',
    label: '操作词',
    tone: '#1f8a5b',
    words: `come, get, give, go, keep, let, make, put, seem, take,
be, do, have, say, see, send, may, will,
about, across, after, against, among, at, before, between, by,
down, from, in, off, on, over, through, to, under, up, with,
as, for, of, till, than,
a, the, all, any, every, little, much, no, other, some, such, that, this,
I, he, you, who,
and, because, but, or, if, though, while, how, when, where, why,
again, ever, far, forward, here, near, now, out, still, then,
there, together, well,
almost, enough, even, not, only, quite, so, very,
tomorrow, yesterday,
north, south, east, west, please, yes`,
  },
  {
    id: 'things',
    label: '一般事物',
    tone: '#2e6f9f',
    words: `account, act, addition, adjustment, advertisement, agreement, air,
amount, amusement, animal, answer, apparatus, approval, argument, art,
attack, attempt, attention, attraction, authority,
back, balance, base, behavior, belief, birth, bit, bite, blood, blow,
body, brass, bread, breath, brother, building, burn, burst, business,
butter,
canvas, care, cause, chalk, chance, change, cloth, coal, color, comfort,
committee, company, comparison, competition, condition, connection,
control, cook, copper, copy, cork, cotton, cough, country, cover,
crack, credit, crime, crush, cry, current, curve,
damage, danger, daughter, day, death, debt, decision, degree, design,
desire, destruction, detail, development, digestion, direction,
discovery, discussion, disease, disgust, distance,
distribution, division, doubt, drink, driving, dust,
earth, edge, education, effect, end, error, event, example, exchange,
existence, expansion, experience, expert,
fact, fall, family, father, fear, feeling, fiction, field, fight, fire,
flame, flight, flower, fold, food, force, form, friend, front, fruit,
glass, gold, government, grain, grass, grip, group, growth, guide,
harbor, harmony, hate, hearing, heat, help, history, hole, hope, hour, humor,
ice, idea, impulse, increase, industry, ink, insect, instrument,
insurance, interest, invention, iron,
jelly, join, journey, judge, jump,
kick, kiss, knowledge,
land, language, laugh, law, lead, learning, leather, letter, level,
lift, light, limit, linen, liquid, list, look, loss, love,
machine, man, manager, mark, market, mass, meal, measure, meat, meeting,
memory, metal, middle, milk, mind, mine, minute, mist, money, month,
morning, mother, motion, mountain, move, music,
name, nation, need, news, night, noise, note, number,
observation, offer, oil, operation, opinion, order, organization,
ornament, owner,
page, pain, paint, paper, part, paste, payment, peace, person, place,
plant, play, pleasure, point, poison, polish, porter, position, powder,
power, price, print, process, produce, profit, property,
prose, protest, pull, punishment, purpose, push,
quality, question,
rain, range, rate, ray, reaction, reading, reason, record, regret, relation, religion,
representative, request, respect, rest, reward, rhythm, rice, river,
road, roll, room, rub, rule, run,
salt, sand, scale, science, sea, seat, secretary, selection, self, sense, servant, sex,
shade, shake, shame, shock, side, sign, silk, silver, sister, size, sky, sleep, slip, slope,
smash, smell, smile, smoke, sneeze, snow, soap, society, son, song, sort, sound, soup,
space, stage, start, statement, steam, steel, step, stitch, stone, stop, story, stretch,
structure, substance, sugar, suggestion, summer, support, surprise, swim, system,
talk, taste, tax, teaching, tendency, test, theory, thing, thought, thunder,
time, tin, top, touch, trade, transport, trick, trouble, turn, twist,
unit, use, value, verse, vessel, view, voice,
walk, war, wash, waste, water, wave, wax, way, weather, week, weight,
wind, wine, winter, woman, wood, wool, word, work, wound, writing,
year`,
  },
  {
    id: 'pictured',
    label: '可见事物',
    tone: '#b36b18',
    words: `angle, ant, apple, arch, arm, army,
baby, bag, ball, band, basin, basket, bath, bed, bee, bell, berry, bird,
blade, board, boat, bone, book, boot, bottle, box, boy, brain, brake,
branch, brick, bridge, brush, bucket, bulb, button,
cake, camera, card, cart, carriage, cat, chain, cheese, chest, chin,
church, circle, clock, cloud, coat, collar, comb, cord, cow, cup,
curtain, cushion,
dog, door, drain, drawer, dress, drop,
ear, egg, engine, eye,
face, farm, feather, finger, fish, flag, floor, fly, foot, fork, fowl, frame,
garden, girl, glove, goat, gun,
hair, hammer, hand, hat, head, heart, hook, horn, horse, hospital, house,
island, jewel,
kettle, key, knee, knife, knot,
leaf, leg, library, line, lip, lock,
map, match, monkey, moon, mouth, muscle,
nail, neck, needle, nerve, net, nose, nut,
office, orange, oven,
parcel, pen, pencil, picture, pig, pin, pipe, plane, plate, plough/plow,
pocket, pot, potato, prison, pump,
rail, rat, receipt, ring, rod, roof, root,
sail, school, scissors, screw, seed, sheep, shelf, ship, shirt, shoe,
skin, skirt, snake, sock, spade, sponge, spoon, spring, square, stamp,
star, station, stem, stick, stocking, stomach, store, street, sun,
table, tail, thread, throat, thumb, ticket, toe, tongue, tooth, town,
train, tray, tree, trousers,
umbrella,
wall, watch, wheel, whip, whistle, window, wing, wire, worm`,
  },
  {
    id: 'qualities',
    label: '性质',
    tone: '#44713b',
    words: `able, acid, angry, automatic, beautiful, black, boiling, bright, broken, brown,
cheap, chemical, chief, clean, clear, common, complex, conscious, cut,
deep, dependent,
early, elastic, electric, equal,
fat, fertile, first, fixed, flat, free, frequent, full,
general, good, great, grey/gray,
hanging, happy, hard, healthy, high, hollow,
important, kind,
like, living, long,
male, married, material, medical, military,
natural, necessary, new, normal,
open,
parallel, past, physical, political, poor, possible, present, private,
probable,
quick, quiet,
ready, red, regular, responsible, right, round,
same, second, separate, serious, sharp, smooth, sticky, stiff, straight,
strong, sudden, sweet,
tall, thick, tight, tired, true,
violent,
waiting, warm, wet, wide, wise,
yellow, young`,
  },
  {
    id: 'opposites',
    label: '反义性质',
    tone: '#8f4d63',
    words: `awake, bad, bent, bitter, blue, certain, cold, complete, cruel,
dark, dead, dear, delicate, different, dirty, dry,
false, feeble, female, foolish, future,
green, ill,
last, late, left, loose, loud, low,
mixed, narrow, old, opposite,
public, rough,
sad, safe, secret, short, shut, simple, slow, small, soft, solid,
special, strange,
thin, white, wrong`,
  },
];

const zh = {
  come: '来', get: '得到', give: '给', go: '去', keep: '保持', let: '让', make: '制作；使', put: '放',
  seem: '似乎', take: '拿；带', be: '是；存在', do: '做', have: '有', say: '说', see: '看见',
  send: '发送', may: '可以；可能', will: '将会', about: '关于', across: '穿过', after: '在之后',
  against: '反对；倚着', among: '在之中', before: '在之前', between: '在两者之间', down: '向下',
  from: '从', over: '在上方', through: '通过', under: '在下面', again: '再一次', enough: '足够',
  tomorrow: '明天', yesterday: '昨天', north: '北', south: '南', east: '东', west: '西', please: '请',
  yes: '是的', account: '账户；叙述', act: '行为；行动', air: '空气', animal: '动物', answer: '回答',
  art: '艺术', attack: '攻击', attention: '注意', authority: '权威', back: '背部；后面',
  balance: '平衡', base: '基础', belief: '信念', birth: '出生', blood: '血液', body: '身体',
  bread: '面包', brother: '兄弟', building: '建筑', business: '生意', care: '照顾', cause: '原因',
  change: '变化', color: '颜色', comfort: '舒适', company: '公司；陪伴', control: '控制',
  country: '国家；乡村', damage: '损害', danger: '危险', daughter: '女儿', day: '一天',
  death: '死亡', decision: '决定', design: '设计', detail: '细节', direction: '方向',
  distance: '距离', drink: '饮料；喝', earth: '地球；土地', education: '教育', effect: '影响',
  end: '结束', event: '事件', example: '例子', experience: '经验', family: '家庭', father: '父亲',
  fear: '害怕', feeling: '感觉', field: '田地；领域', fire: '火', flower: '花', food: '食物',
  friend: '朋友', fruit: '水果', glass: '玻璃；杯子', government: '政府', grass: '草',
  group: '群组', help: '帮助', history: '历史', hope: '希望', hour: '小时', idea: '想法',
  industry: '工业', interest: '兴趣；利息', journey: '旅程', knowledge: '知识', language: '语言',
  law: '法律', learning: '学习', letter: '字母；信', light: '光；轻的', list: '清单',
  love: '爱', machine: '机器', man: '男人', market: '市场', meal: '一餐', memory: '记忆',
  milk: '牛奶', money: '钱', month: '月份', mother: '母亲', mountain: '山', music: '音乐',
  name: '名字', nation: '国家', need: '需要', news: '新闻', night: '夜晚', noise: '噪音',
  number: '数字', offer: '提供', order: '顺序；命令', page: '页面', pain: '疼痛', paper: '纸',
  peace: '和平', person: '人', place: '地方', plant: '植物；种植', play: '玩；戏剧',
  point: '点；观点', power: '力量', price: '价格', process: '过程', question: '问题',
  rain: '雨', reason: '原因', record: '记录', respect: '尊重', river: '河流', road: '道路',
  room: '房间', rule: '规则', salt: '盐', school: '学校', science: '科学', sea: '海',
  sense: '感觉；意义', sister: '姐妹', size: '大小', sky: '天空', sleep: '睡眠', smile: '微笑',
  snow: '雪', society: '社会', son: '儿子', song: '歌曲', sound: '声音', space: '空间',
  start: '开始', story: '故事', summer: '夏天', system: '系统', talk: '谈话', taste: '味道',
  test: '测试', thing: '东西', thought: '想法', time: '时间', trade: '贸易', trouble: '麻烦',
  use: '使用', value: '价值', view: '视野；看法', voice: '声音', walk: '走路', war: '战争',
  water: '水', weather: '天气', week: '星期', wind: '风', winter: '冬天', woman: '女人',
  wood: '木头', word: '单词', work: '工作', writing: '写作', year: '年',
  angle: '角', apple: '苹果', arm: '手臂', baby: '婴儿', bag: '包', ball: '球', bed: '床',
  bird: '鸟', book: '书', bottle: '瓶子', boy: '男孩', brain: '大脑', bridge: '桥',
  camera: '相机', card: '卡片', cat: '猫', chain: '链条', clock: '钟', cloud: '云',
  coat: '外套', cow: '奶牛', cup: '杯子', dog: '狗', door: '门', ear: '耳朵', egg: '蛋',
  eye: '眼睛', face: '脸', farm: '农场', finger: '手指', fish: '鱼', floor: '地板',
  foot: '脚', garden: '花园', girl: '女孩', hair: '头发', hand: '手', hat: '帽子',
  head: '头', heart: '心', horse: '马', house: '房子', island: '岛', key: '钥匙',
  knee: '膝盖', knife: '刀', leaf: '叶子', leg: '腿', library: '图书馆', line: '线',
  map: '地图', moon: '月亮', mouth: '嘴', neck: '脖子', nose: '鼻子', office: '办公室',
  orange: '橙子；橙色', pen: '钢笔', pencil: '铅笔', picture: '图片', plate: '盘子',
  pocket: '口袋', potato: '土豆', prison: '监狱', ring: '戒指', roof: '屋顶',
  seed: '种子', sheep: '羊', shirt: '衬衫', shoe: '鞋', skin: '皮肤', snake: '蛇',
  spoon: '勺子', spring: '春天；弹簧', star: '星星', street: '街道', sun: '太阳',
  table: '桌子', tooth: '牙齿', town: '城镇', train: '火车', tree: '树', umbrella: '伞',
  wall: '墙', watch: '手表；看', wheel: '轮子', window: '窗户', wing: '翅膀',
  able: '能够的', acid: '酸的', angry: '生气的', automatic: '自动的', beautiful: '美丽的',
  black: '黑色的', bright: '明亮的', broken: '破损的', brown: '棕色的', cheap: '便宜的',
  clean: '干净的', clear: '清楚的', common: '常见的', deep: '深的', early: '早的',
  equal: '相等的', fat: '胖的；脂肪', first: '第一的', flat: '平的', free: '自由的；免费的',
  full: '满的', good: '好的', great: '伟大的', happy: '快乐的', hard: '困难的；硬的',
  healthy: '健康的', high: '高的', important: '重要的', kind: '友善的；种类',
  living: '活着的', long: '长的', natural: '自然的', necessary: '必要的', new: '新的',
  open: '打开的', poor: '贫穷的；差的', possible: '可能的', present: '现在的；礼物',
  quick: '快的', quiet: '安静的', ready: '准备好的', red: '红色的', right: '正确的；右边',
  round: '圆的', serious: '严肃的', sharp: '锋利的', smooth: '光滑的', strong: '强壮的',
  sweet: '甜的', tall: '高的', tired: '疲惫的', true: '真实的', warm: '温暖的',
  wet: '湿的', wide: '宽的', wise: '明智的', yellow: '黄色的', young: '年轻的',
  awake: '醒着的', bad: '坏的', bitter: '苦的', blue: '蓝色的', cold: '冷的',
  dark: '黑暗的', dead: '死的', different: '不同的', dirty: '脏的', dry: '干的',
  false: '错误的', female: '女性的', foolish: '愚蠢的', future: '未来的', green: '绿色的',
  late: '迟的', left: '左边', loud: '大声的', low: '低的', narrow: '窄的',
  old: '老的；旧的', public: '公共的', rough: '粗糙的', sad: '悲伤的', safe: '安全的',
  secret: '秘密的', short: '短的', shut: '关闭的', simple: '简单的', slow: '慢的',
  small: '小的', soft: '软的', thin: '薄的；瘦的', white: '白色的', wrong: '错误的',
};

const ipa = {
  come: '/kʌm/', get: '/ɡet/', give: '/ɡɪv/', go: '/ɡoʊ/', keep: '/kiːp/', let: '/let/',
  make: '/meɪk/', put: '/pʊt/', seem: '/siːm/', take: '/teɪk/', have: '/hæv/', say: '/seɪ/',
  see: '/siː/', about: '/əˈbaʊt/', enough: '/ɪˈnʌf/', tomorrow: '/təˈmɑːroʊ/',
  account: '/əˈkaʊnt/', animal: '/ˈænɪməl/', answer: '/ˈænsər/', attention: '/əˈtenʃən/',
  body: '/ˈbɑːdi/', brother: '/ˈbrʌðər/', business: '/ˈbɪznəs/', country: '/ˈkʌntri/',
  daughter: '/ˈdɔːtər/', education: '/ˌedʒuˈkeɪʃən/', experience: '/ɪkˈspɪriəns/',
  family: '/ˈfæməli/', flower: '/ˈflaʊər/', friend: '/frend/', knowledge: '/ˈnɑːlɪdʒ/',
  language: '/ˈlæŋɡwɪdʒ/', machine: '/məˈʃiːn/', mountain: '/ˈmaʊntən/', question: '/ˈkwestʃən/',
  science: '/ˈsaɪəns/', society: '/səˈsaɪəti/', water: '/ˈwɔːtər/', weather: '/ˈweðər/',
  apple: '/ˈæpəl/', baby: '/ˈbeɪbi/', bottle: '/ˈbɑːtəl/', camera: '/ˈkæmərə/',
  chocolate: '/ˈtʃɑːklət/', orange: '/ˈɔːrɪndʒ/', picture: '/ˈpɪktʃər/', umbrella: '/ʌmˈbrelə/',
  beautiful: '/ˈbjuːtɪfəl/', comfortable: '/ˈkʌmftəbəl/', different: '/ˈdɪfərənt/',
  important: '/ɪmˈpɔːrtənt/', necessary: '/ˈnesəseri/', possible: '/ˈpɑːsəbəl/',
};

const cleanToken = (word) => word.trim().replace(/\s+/g, ' ').replace(/[.。]/g, '');

export const groups = rawGroups.map((group) => ({
  ...group,
  count: group.words.split(',').map(cleanToken).filter(Boolean).length,
}));

export const words = rawGroups.flatMap((group) =>
  group.words
    .split(',')
    .map(cleanToken)
    .filter(Boolean)
    .map((word, index) => {
      const speakWord = word.includes('/') ? word.split('/')[0].trim() : word;
      return {
        id: `${group.id}-${index}-${speakWord.toLowerCase()}`,
        word,
        speakWord,
        groupId: group.id,
        groupLabel: group.label,
        tone: group.tone,
        zh: zh[speakWord] || `${group.label}词`,
        ipa: ipa[speakWord] || '',
      };
    }),
);
